### ISSUE TITLE
Story::As an admin, partner and operations lead, I should be able to view the Gross Percentage % by providing the inputs required to calculate that GP.

### ISSUE THREAD

**Issue by Adharshd** [rkulkar5/OnlineTAT#101]

**Comment by sivabluemix** [comment]
logged in as DWP-Admin and trying to calculate GP for a candidate and getting below error, can some one tell why this error is coming , is it WTD if yes, whats the business condition to calculate GP.,

![image](https://user-images.githubusercontent.com/24892801/93672092-2161f280-faa0-11ea-90e2-4f39d4f71b6a.png)

**Comment by rashmidevapura** [comment]
@Siva: Assigning back to Siva for closure after verifition...as this details already communicated to him.

**Comment by rashmidevapura** [comment]
@sivabluemix : It is closed before assigning... please verify and provide your comment.
