### ISSUE TITLE
Story::As a Sector Tech SME, upload questions in bulk to one,or many all the sccounts in sector

### ISSUE THREAD

**Issue by Adharshd** [rkulkar5/OnlineTAT#106]

**Comment by sivabluemix** [comment]
@Adharshd 
TechSME- BulkUpload Questions - for more than one account scenario.,
Logged in as SectorTechSME on Cloud-TST, I have uploaded 2 questions (for DWP,NHS accounts) and its poped me saying 2 questions were added successfully. But, In view Quesitons, I can see only one question out of 2 added.,

![image](https://user-images.githubusercontent.com/24892801/93671668-d8f50580-fa9c-11ea-8aea-d77fa290cd9f.png)

Can you please assign this to some one who can look into it.,
