### ISSUE TITLE
Super Admin - Users List is not fetching details correctly

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#117]
a)	‘User list’ is displaying different users while navigating back and forth from ‘update/ Cancel’ screen. When logged in only admin users are displayed in Users list and when navigated back from ‘update/ Cancel’ screen it is showing partner/SME details of all accounts.
b)	Log out option is also not available, when navigated back from ‘update/ Cancel’ screen.
![image.png](https://images.zenhubusercontent.com/5ee70571210454c96d9aacda/d9734913-480d-4852-a277-c4b9d50687b1)

**Comment by Adharshd** [comment]
@Harshitha-Edpuganti Can you please check? I think, among other things, this is caused by wrong link navigation when we click on "Update" in edit user?

**Comment by Harshitha-Edpuganti** [comment]
The issues mentioned above are fixed and checked-in.

**Comment by Adharshd** [comment]
@Teja-swi The issue is fixed - please test the same by taking latest from GIT.

**Comment by Teja-swi** [comment]
Hi Harshitha,


Currently the list is fetching only admin users, But not fetching sector level SME, Partner, Operations details.

**Comment by Harshitha-Edpuganti** [comment]
Hi Tejaswi,

We can see all the sector level sme,partner,ops and Account level admins in the Users List even after Edit screen Update/Cancel. Please check if you have latest code.

**Comment by Teja-swi** [comment]
As discussed, this works fine for 'SECTOR'. Hence, closing this issue.
