### ISSUE TITLE
'Change Password' option is not populating for admins created by Super Admin

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#118]
Created account level admin as super admin. But change password option is not available, when logged-in as admin. This is working correctly for SME /partner/management.

**Comment by Adharshd** [comment]
@Harshitha-Edpuganti Can you check this? 

I am sure the same issue exists for admin, TechSMEs, Partners, Operations users as well in adddition to Super Admin. Thank you

**Comment by Harshitha-Edpuganti** [comment]
Hi Adharsh, only admin users don't get change password screen as per our old design.
Hi Tejaswi, I have fixed this. Please check and confirm.

**Comment by Teja-swi** [comment]
working now
