### ISSUE TITLE
Super admin is able to 'update' account level admin as 'sector' level admin

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#119]
Super admin is not able to create sector level admin which is as per design. But Later super admin can update an account level admin to sector level admin. Similarly, roles can be changed to account level sme/partners/ops.

Colliding with requirement: There is no sector admin and thus it indicates user registration will be done only by account level admins.
![image.png](https://images.zenhubusercontent.com/5ee70571210454c96d9aacda/bdd073c9-ee31-4385-b738-65af1de5bfde)

**Comment by Adharshd** [comment]
@Harshitha-Edpuganti Can you please check this and let me know whether this is an issue in coding or only in backend data which Tejaswi ahs? Thank you.

**Comment by Harshitha-Edpuganti** [comment]
Hi Tejaswi
This issue has been fixed with Rashmi's latest code changes. Please check and confirm.

**Comment by Teja-swi** [comment]
working now
