### ISSUE TITLE
Questions added by Sector SME to multiple accounts(in an array) were not reflecting in 'View questions' list of  account level admin.

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#120]
Questions added by Sector SME to multiple accounts(in an array) were not reflecting in the 'View questions' list of  account level admin.

**Comment by Adharshd** [comment]
@deenagesnagesh Can you please check this? Reach out to Tejaswi for any questions. Thank you.

**Comment by deekshanagesh08** [comment]
Fixed, test when deployed on cloud

**Comment by Teja-swi** [comment]
Issue fixed
