### ISSUE TITLE
When logged-in as a user , unable to see the user name who has logged in ..applicable to all webpages

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#121]
When logged-in as a user , unable to see the user name who has logged in ..applicable to all webpages.

For example, if we login to a gmail account, we could see user name and email address at the top right corner along with log out option.

**Comment by Adharshd** [comment]
To be discussed - with the team and Amit - as this is a new requirement.

**Comment by Harshitha-Edpuganti** [comment]
@Teja-swi Fixed

**Comment by Teja-swi** [comment]
Issue fixed for Super Admin as well
