### ISSUE TITLE
Super Admin - Users List Filters are missing

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#122]
Filters are missing to search a particular user from 'Users List' in Super Admin.

**Comment by Adharshd** [comment]
@Harshitha-Edpuganti the expectation is to add Filters similar to what we have in SME, Partner and Operations/Managment user list.

**Comment by Adharshd** [comment]
Since this is not discussed before - marked as new requirement.

**Comment by rashmidevapura** [comment]
Added filters..checked in ..please verify

**Comment by Nagalakshmi97** [comment]
Working Fine
