### ISSUE TITLE
Super admin - Add user

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#123]
User role has to be selected prior to Account.  A message needs to be displayed like ' select user role first' when trying to select value of Account initially.

**Comment by Adharshd** [comment]
@Harshitha-Edpuganti Can you please this whether this is required? Thank you.

**Comment by Adharshd** [comment]
As of now - the candidate is the only person who can change password. 

For other users - we can discuss later about the Change Password options.

**Comment by rashmidevapura** [comment]
Added a message "Select user Role first" on add user. checked in code ... please verify once deployed in the code...

**Comment by rashmidevapura** [comment]
Added sample screen from local:
![image](https://user-images.githubusercontent.com/61687054/94684217-5e05d780-0345-11eb-86d7-b8f0f352815f.png)

**Comment by Nagalakshmi97** [comment]
Working Fine
