### ISSUE TITLE
Any user role - Blank Page appears when user tries to refresh the page. 

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#124]
Any user role - Blank Page appears when user tries to refresh the page.

**Comment by Adharshd** [comment]
@rkulkar5 Can you tell me whether this will be solved when the code is deployed in IBM Cloud?

**Comment by deekshanagesh08** [comment]
Defect fixed. Kindly test.

**Comment by Tatireddysreevani** [comment]
fixed...
