### ISSUE TITLE
Account level admin - Navigation Bar

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#125]
a) Currently section is not highlighting when an admin is navigating through various sections like Manage users , Mange Questions, Manage metadata etc

![image](https://user-images.githubusercontent.com/66815529/92884008-128b9800-f42f-11ea-9d66-db2f8571ff44.png)

b)Navigation bar - In order to see various options available under each section, we need to click twice on the section.

![image](https://user-images.githubusercontent.com/66815529/92884086-2505d180-f42f-11ea-88b2-afbe197b5f34.png)

**Comment by Adharshd** [comment]
To be checked with the team in Scrum call on 11th September.

**Comment by rkulkar5** [comment]
I have tried to fix this by making changes to CSS, but it works only for parent links 
It does not work when clicked on the child links

**Comment by rashmidevapura** [comment]
Parent link is working fine as informed by Rajesh.. and the same as checked in.. for child drop down values it is not working..

**Comment by ranjeetibm** [comment]
Fixed.
Please retest once code is redeployed to cloud.

**Comment by Tatireddysreevani** [comment]
![image](https://user-images.githubusercontent.com/61975055/104881749-e1e0df80-5987-11eb-9dae-077a449e69ab.png)

still its not working for child dropdown links

**Comment by Tatireddysreevani** [comment]
Rajesh told to try after clearing cache in browser, did the same and its working fine now
![image](https://user-images.githubusercontent.com/61975055/104884718-d643e780-598c-11eb-994b-10c24b3baf4f.png)
