### ISSUE TITLE
Add Candidate _ Mobile Number

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#127]
Currently TAT tool accepts mobile number less than 10-digit

![image.png](https://images.zenhubusercontent.com/5ee70571210454c96d9aacda/9912c3d2-e44e-4b8b-a9a1-04e26c652dd8)

**Comment by Adharshd** [comment]
To be discussed in 15th Sept Scrum Call.

**Comment by Adharshd** [comment]
@Harshitha-Edpuganti please check this issue as dicussed.

**Comment by rashmidevapura** [comment]
please verify and close

**Comment by Teja-swi** [comment]
Issue fixed
