### ISSUE TITLE
Logged In as Super (username super) user and Expecting pagenation should show Button to First and Last !!

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#128]
[SuperUser_PaginationIssue.docx](https://github.com/rkulkar5/OnlineTAT/files/5219113/SuperUser_PaginationIssue.docx)

Hi @Team,
I logged in as 'super user' and expecting the pagination should show the buttons to 'First' and 'Last' page along with next.,

**Comment by sivabluemix** [comment]
@Adharshd  Please notify us once the relevant code is uploaded on Cloud.,

**Comment by rashmidevapura** [comment]
Fixed the issue...please verify

**Comment by Teja-swi** [comment]
![image](https://user-images.githubusercontent.com/66815529/95303921-79229b00-08a1-11eb-9c04-430d1dc44e5e.png)
Issue fixed
