### ISSUE TITLE
Singed in as 'super' user and trying to create an SME but its not displaying account in account drop down.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#129]
[SuperUser_AccountNotDisplaying.docx](https://github.com/rkulkar5/OnlineTAT/files/5219146/SuperUser_AccountNotDisplaying.docx)

Accounts drop down is not populating thought  I selected rest all other fields.,

**Comment by Adharshd** [comment]
@rashmidevapura can you please check this?

**Comment by rashmidevapura** [comment]
@Adharshd : Working as expected and shown as in demo...test it and assign back if fine

**Comment by Adharshd** [comment]
@sivabluemix This is how it is supposed to work as Super Admin only has access to create Sector-level users.

**Comment by sivabluemix** [comment]
Agreed !!
