### ISSUE TITLE
Singed as Super user and noticed the content of nav bar links are not displaying completely.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#130]
[SuperUser_Links (nav bar) content is not displaying completely.docx](https://github.com/rkulkar5/OnlineTAT/files/5219163/SuperUser_Links.nav.bar.content.is.not.displaying.completely.docx)

**Comment by Adharshd** [comment]
@Harshitha-Edpuganti Can you please check the same? 

As I am facing compilation issues.

**Comment by ranjeetibm** [comment]
Can you please test this issue again. Now this issue doesn't exist.

**Comment by sivabluemix** [comment]
Fix working and closing the defect.,
