### ISSUE TITLE
NavBar Missing on WorkFlowMgmt after save.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#131]
[WorkFlow-Mgmt-NavBar Missing.docx](https://github.com/rkulkar5/OnlineTAT/files/5219237/WorkFlow-Mgmt-NavBar.Missing.docx)

**Comment by Adharshd** [comment]
@rkulkar5 Can you please check this issue?

**Comment by rkulkar5** [comment]
This has been taken by the team
Please verify and close the issue

**Comment by sivabluemix** [comment]
Fix is working & Closing the defect.,
