### ISSUE TITLE
Soring by Status is not working when logged in as admin user

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#132]
[SortingByStatus Not working When Logged In with Admin User.docx](https://github.com/rkulkar5/OnlineTAT/files/5219249/SortingByStatus.Not.working.When.Logged.In.with.Admin.User.docx)

**Comment by Adharshd** [comment]
@ranjeetibm Can you please check the same?

**Comment by ranjeetibm** [comment]
Can you please test this again. I have tested with account level admin and it's working fine.

**Comment by sivabluemix** [comment]
Fix working and closing the defect.,
