### ISSUE TITLE
Logged in as super user - trying to create a multi account sme, but accounts are not displaying.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#133]
![LoggedInAs Super User - Why Rest of the Accounts are not displaying ](https://user-images.githubusercontent.com/24892801/93103758-ebd69700-f6a4-11ea-9cee-9df8b4ad7764.PNG)

**Comment by Adharshd** [comment]
@rashmidevapura Can you assist Siva in creating the multiple account SME?

**Comment by Adharshd** [comment]
@sivabluemix : As discussed in the call, we cant create multi-account users using super admin.

**Comment by sivabluemix** [comment]
We can only create admin related to multi accounts but SME can only create at the Sector level, not at the multi-account level.,
