### ISSUE TITLE
Logged in as superadmin, created a sector sme 'sivasectorsme1' but its not displaying in userlist.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#134]
![superadmin - Created a sector level sme 'sivasectorsme1' but its not displaying in userlist](https://user-images.githubusercontent.com/24892801/93104132-5daee080-f6a5-11ea-9475-d039421628da.PNG)

**Comment by Adharshd** [comment]
@ranjeetibm Temporarily assigned to you as Harshitha is not available.

**Comment by Adharshd** [comment]
Assigned to @Harshitha-Edpuganti

**Comment by Harshitha-Edpuganti** [comment]
Hi Siva,
It's working fine for me. Can you please check if you have uppercase 'SECTOR' in account collection, if not please change it and try as it should be in upper case.

**Comment by sivabluemix** [comment]
Hi @Harshitha-Edpuganti ,
I Just tried in Cloud TST also, there also its not working.
1) I entered the data required to create a sector level sme using Superadmin.
2) clicked register button and got a popup saying, user created successfully.
3) Notice, the user-list (bottom of the same page) is not populated with the newly created sector level sme.

Can you try on cloud and let me know !!

My local database got accidentally destroyed, i need to see how to restore.,

**Comment by Tatireddysreevani** [comment]
working as expected
