### ISSUE TITLE
[Cloud-TST] Logged in as DWPAdmin (shared by rajesh) and trying to create a position.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#136]
defect#1)  the space between 'save, reset, cancel' is not equal.,
defect#2)  Clicked save button but the form or data entered is not saved.,

**Comment by Tatireddysreevani** [comment]
save button is working but  the space between 'save, reset, cancel' is not equal

**Comment by deekshanagesh08** [comment]
Issue is fixed, Kindly test once deployed on cloud

**Comment by Teja-swi** [comment]
![image](https://user-images.githubusercontent.com/66815529/95429526-252eb980-0968-11eb-8192-c354222b04f7.png)

Issue fixed
