### ISSUE TITLE
[Cloud-TST] Logged in with DWPAdmin - On Test View Results - Trying to test for email filter - Believe not working

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#137]
I gave 'siv' in the email filter but there is no candidate with the e-mail of 'siv' content, but then why its displaying a single row.,
![EmailFilter_View Test Results](https://user-images.githubusercontent.com/24892801/93138831-91a2f980-f6d7-11ea-9831-f6741f53a1ee.PNG)

**Comment by Adharshd** [comment]
@rashmidevapura Can you check the same? I believe this could be the same scenario in local repo.

**Comment by rashmidevapura** [comment]
working fine here ..please check again and confirm

**Comment by rashmidevapura** [comment]
please check and confirm

**Comment by sivabluemix** [comment]
I have tried again, but seems its not working as expected, Please check,
![Uploading image.png…]()

**Comment by rashmidevapura** [comment]
fixed..please verify once deployed on cloud

**Comment by Tatireddysreevani** [comment]
working......
