### ISSUE TITLE
[Cloud-TST] Logged in as DWPAdmin and trying to create a JOB-Role 'Project Manager Assessment' - clicked save but save button funcitonality not working.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#138]
![JobRole - Save Functionality Not working](https://user-images.githubusercontent.com/24892801/93139215-37566880-f6d8-11ea-93c9-472ee5a694b7.PNG)

**Comment by Adharshd** [comment]
@rkulkar5 Can you check the same? Thank you.

**Comment by Tatireddysreevani** [comment]
working........
