### ISSUE TITLE
[Cloud-TST] Created a new candidate and trying to set the password using forgot password, but not working.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#139]
I entered the valid candidate name and date of joining, but its saying invalid data entered, can you please guide me here.,
![ForgotPwd_Notworking](https://user-images.githubusercontent.com/24892801/93139717-3245e900-f6d9-11ea-93db-c9bed4301c7c.PNG)

**Comment by Adharshd** [comment]
@rkulkar5 Can you please check this issue in the cloud?

**Comment by rkulkar5** [comment]
Hi
I have verified the issue and it is working fine 
Here username is nothing but the email ID (the name appearing in view page is his the name, not to be used for login)
Please verify and close if it works (using emailID as the login id/username)
Thanks

**Comment by sivabluemix** [comment]
Using E-mailId, its working., so closing.,
