### ISSUE TITLE
Task:: Add technological streams function for TechSME

### ISSUE THREAD

**Issue by Adharshd** [rkulkar5/OnlineTAT#141]
Both the sector and account level TechSME - should be able to add new technology streams(which are not available in the technology stream drop-down).

**Comment by Teja-swi** [comment]
This is not available for account SME and sector SME.

**Comment by Adharshd** [comment]
@Teja-swi : you should be able to Add Tech. Streams in sector and account level tech sme under "Manage Question" tab in the option shown below. 
![image](https://user-images.githubusercontent.com/8875515/94710193-2d816600-0364-11eb-8215-522682792038.png)

**Comment by Teja-swi** [comment]
Working FIne, It could have been better if this is divided into a different section.

**Comment by deekshanagesh08** [comment]
Defect fixed. Kindly test

**Comment by Tatireddysreevani** [comment]
Still getting same screen, it didn't divided into seperate section
![image](https://user-images.githubusercontent.com/61975055/103063856-9598be80-45d8-11eb-9270-4702a7f4b338.png)
