### ISSUE TITLE
[Cloud TST]  Logged in as account level partner and clicked on initiate interview, not able to access pre technical interview form  

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#143]
When we click on the link for “you can access the pre technical interview form here” no questions are loading, the screen is coming like this.

![image](https://user-images.githubusercontent.com/61975055/93207652-e480bd80-f778-11ea-8431-89de78697a86.png)

**Comment by Adharshd** [comment]
@Tatireddysreevani Can you confirm that you have loaded the pre-tech questions in backend? 

@ranjeetibm can you please check this issue whenever possible?

**Comment by Tatireddysreevani** [comment]
yes, pre-tech questions are there in backend

**Comment by ranjeetibm** [comment]
Working as expected. Please retest.

**Comment by Tatireddysreevani** [comment]
Still not able to access pre technical interview form

**Comment by ranjeetibm** [comment]
Can you please tell me how you have created the data. After assessment are you getting pre technical form with all the questions.
I have retested and found no issue. please find the screenshot attached.

------------------------------------------------------------------------------
<img width="929" alt="Defect143_Result" src="https://user-images.githubusercontent.com/61973926/94019602-98182c00-fdcf-11ea-9d6d-c3233c945bc6.PNG">

**Comment by rkulkar5** [comment]
data fix done, please verify and close

**Comment by Teja-swi** [comment]
Similar to SME , Issue with Question 16

![Uploading image.png…]()

**Comment by Tatireddysreevani** [comment]
Issue fixed
