### ISSUE TITLE
Logged in as account level partner, need to do some alignment changes in initiate partner interview screen

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#144]
![image](https://user-images.githubusercontent.com/61975055/93209873-58709500-f77c-11ea-8568-0898d41df429.png)

1.	In this screen Initiate Partner Interview tab has moved to right side slightly.
2.	Job Role, Online Test Result, you can access the Pre-Technical-Interview form here and Technical Interview Result has moved 
        to left side.
3.	Technical Interview Feedback is not coming on the same line, its going upside

**Comment by Adharshd** [comment]
@rkulkar5 Can you please check these issues?

**Comment by rashmidevapura** [comment]
@rkulkar5 : Fixed the issue..please verify..if it is fine ...assign to test team...

**Comment by rkulkar5** [comment]
@Tatireddysreevani Please verify and close if the changes stratifies you - Thanks

**Comment by Tatireddysreevani** [comment]
Issue got resolved
