### ISSUE TITLE
Account Level Partner- candidate details screen and candidate assessment details screen has not updated 

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#145]
In project assignment screen, when we click on candidate name and online test result of project assignment queue the screens has not updated.

![image](https://user-images.githubusercontent.com/61975055/93212513-527cb300-f780-11ea-83e7-83eb901562c4.png)

![image](https://user-images.githubusercontent.com/61975055/93212548-5a3c5780-f780-11ea-8f67-c306bb022517.png)

**Comment by Adharshd** [comment]
Changes to be done - after Sprint 10 work.

**Comment by Harshitha-Edpuganti** [comment]
fixed
