### ISSUE TITLE
Account Level Partner- It would be better to provide search criteria in open position list for searching open positions easily

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#146]
Search criteria has not provided in this open positions list, it would be better to add search criteria for finding open positions easily when there is more number of open positions.

![image](https://user-images.githubusercontent.com/61975055/93213025-f9614f00-f780-11ea-9b61-2c424b40dbbe.png)

**Comment by Adharshd** [comment]
Marked as new requirement.

**Comment by rashmidevapura** [comment]
Added filters..checked in..please verify once deployed in cloud..

**Comment by Tatireddysreevani** [comment]
Ok rashmi
