### ISSUE TITLE
Super Admin - Add user 

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#150]
After selecting Account in Add user, still 'choose' is displaying 

![image.png](https://images.zenhubusercontent.com/5ee70571210454c96d9aacda/c566039d-1ea1-4762-86c9-09110d7a4ad0)

**Comment by Harshitha-Edpuganti** [comment]
Hi Tejaswi,
Choose disabled option has be removed as it's not required.Please check.

**Comment by Teja-swi** [comment]
Issue fixed

**Comment by Teja-swi** [comment]
Similar issue observed in Admin screen

![image](https://user-images.githubusercontent.com/66815529/93593145-24da7880-f9d1-11ea-8bda-0878552120ab.png)

**Comment by Harshitha-Edpuganti** [comment]
@Teja-swi fixed

**Comment by Teja-swi** [comment]
Issue fixed
