### ISSUE TITLE
Admin related to one account  is able to create candidate for other account.

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#151]
Admin related to one account  is able to create candidate for other account. For Example, DWP admin is able to create candidate for NHS

**Comment by Adharshd** [comment]
@Teja-swi This change is part of ongoing Sprint-10 scope(Under "Screens: Add Candidate") and hence this can be tested once this task is complete.

**Comment by Teja-swi** [comment]
IN Sprint-10 this requirement has been changed

**Comment by Teja-swi** [comment]
IN Sprint-10 this requirement has been changed
