### ISSUE TITLE
Account level admin - View Candidate

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#154]
If a candidate is active, the Action should display ' Disable'

![image.png](https://images.zenhubusercontent.com/5ee70571210454c96d9aacda/894c91c1-3536-46b0-92d4-aabb90b31648)

**Comment by Adharshd** [comment]
@ranjeetibm Can you please check this issue? 

I think we took care of this in bootstrap- might have missed in AM.

**Comment by ranjeetibm** [comment]
its working as expected ..can you please test it again.

**Comment by ranjeetibm** [comment]
I tested this. Looks its working as expected...Can you please test it again.

**Comment by Teja-swi** [comment]
This is working fine now
