### ISSUE TITLE
Logged in as DWPAdmin and clicked on Manage Openseats

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#155]
Label mismatch.,
![DWPAdmin-ManageOpenSeats](https://user-images.githubusercontent.com/24892801/93358487-73550f00-f839-11ea-966b-e408ca86a9e6.PNG)

**Comment by rashmidevapura** [comment]
Please verify and close

**Comment by sivabluemix** [comment]
Fix is working, so closing the defect.,
