### ISSUE TITLE
[Cloud-TST] Manage OpenSeat > Add OpenSeat under DWP-Admin 

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#156]
[Cloud-TST]Logged in as DWP-Admin and clicked Manag Openseat > Add OpenSeat, Entered the data and click on Save, Save  button functionality is not working.,

**Comment by Adharshd** [comment]
@rkulkar5 Since this functionality is working for me in local - can you check the same in IBM cloud?

**Comment by Tatireddysreevani** [comment]
yes, its working.....
