### ISSUE TITLE
[Cloud-TST] Why are we displaying other Accounts in account drop down when we logged in as 'DWP-Admin'

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#157]
![Creating_SME_Using_DWPAdminCreds](https://user-images.githubusercontent.com/24892801/93359541-a2b84b80-f83a-11ea-926b-4c0d755899f9.PNG)

Logged in as dwpadmin - Create User (as sme) - expecting only DWP as the value under Account drop down, but display all accounts.,

**Comment by Adharshd** [comment]
This will done as part of Sprint-10

**Comment by sivabluemix** [comment]
@Adharshd  Can you please notify us when the code is deployed in cloud.,

**Comment by Tatireddysreevani** [comment]
working......
