### ISSUE TITLE
[Cloud-TST] JRSS - TechStream Mapping Issue

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#158]
I logged in as DWP-SME, initiated interview to a candidate, 
When giving score to a skill, I can see 'JAVA' is by default loaded (agree) but when click + symbol, its added an another record of Python., Why Python is displaying here ?.,

Refer screenshots.,

![JRSS_2_TechMappingIssue](https://user-images.githubusercontent.com/24892801/93362785-553ddd80-f83e-11ea-960d-60ef014e58de.PNG)
![JRSS_2_TechMappingIssue_1](https://user-images.githubusercontent.com/24892801/93362789-566f0a80-f83e-11ea-8a7c-8965ad30f684.PNG)

**Comment by Adharshd** [comment]
@rashmidevapura Can you please check this?

**Comment by rashmidevapura** [comment]
@Harshitha-Edpuganti : Assigning to Harshita to check

**Comment by Harshitha-Edpuganti** [comment]
@sivabluemix  This is working as per requirement. Technology stream field should fetch all the available streams across all JRSS and when you click on plus button it will show the stream names one by one from collection.

**Comment by sivabluemix** [comment]
Closing as the Dev classified as WTD.,
