### ISSUE TITLE
[Cloud-TST] DWPSME - Initiate Interview - Cosmetic Change

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#159]
Can you consider to remove the given space.,
![SME-Initiate_Interview-Cosmetic Change](https://user-images.githubusercontent.com/24892801/93363008-959d5b80-f83e-11ea-8e22-bd8244930cff.PNG)

**Comment by Adharshd** [comment]
Marked as New Requirement

**Comment by rashmidevapura** [comment]
Fixed ..please verify once deployed to cloud...

**Comment by Teja-swi** [comment]
Issue fixed

![image](https://user-images.githubusercontent.com/66815529/95310279-db7f9980-08a9-11eb-9602-bff1269d756e.png)
