### ISSUE TITLE
[Cloud-TST] DWP-SME Adding a question, Why we are displaying other accounts in Account drop down?.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#160]
![DWPSME-QuestionAdd](https://user-images.githubusercontent.com/24892801/93364018-f24d4600-f83f-11ea-923c-656194f24d84.PNG)

**Comment by Adharshd** [comment]
@sivabluemix this will be done as part of Sprint-10.

**Comment by sivabluemix** [comment]
@Adharshd  Can you please notify us once the code is uploaded in Cloud.,

**Comment by Teja-swi** [comment]
Issue fixed
![Uploading image.png…]()
