### ISSUE TITLE
[Cloud-TST] Logged In as DWP-SME, View Quesitons Page - sorting is not working.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#161]
![DWPSME-ViewQuestion-SortingNotWorking](https://user-images.githubusercontent.com/24892801/93370485-cc786f00-f848-11ea-944e-21e9730929f9.PNG)

**Comment by Adharshd** [comment]
@deekshanagesh08 @deenagesnagesh Can you please check this issue? Even though this is working in local - this might be an issue on cloud.

**Comment by Tatireddysreevani** [comment]
closing issue as its working fine
