### ISSUE TITLE
[Cloud-TST] DWP-Admin loggedIn, Creating Partner - Why Are we seeing other accounts other than DWP.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#162]
![DWPAdmin-CreatingPartnerforDwp_Why OTherAccounts](https://user-images.githubusercontent.com/24892801/93371085-b0c19880-f849-11ea-9b88-0fa10be8dada.PNG)

**Comment by Adharshd** [comment]
This change will be done as part of Sprint-10.

**Comment by sivabluemix** [comment]
@Adharshd  Can you notify us once the relevant code is uploaded to cloud.,

**Comment by Tatireddysreevani** [comment]
working.........
