### ISSUE TITLE
[Cloud-TST] DWP-Partner Logged In, Alignment is not good.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#163]
![DWP-Partner_Tables Alignment Not Good](https://user-images.githubusercontent.com/24892801/93371308-0ac25e00-f84a-11ea-829f-25897103ed9c.PNG)

**Comment by Adharshd** [comment]
@rashmidevapura Can you please check this issue?

**Comment by rashmidevapura** [comment]
fixed

**Comment by sivabluemix** [comment]
fix working and closing the defect.,
