### ISSUE TITLE
[Cloud-TST] LoggedIn As DWP-Partner - DashBoard - Techncal Interview DashBoard Working - After clicking 'Clear' the data is not brining back to original state.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#164]
![DWP_Partner_DashBoard_SearchWorking_ClearNotWorking](https://user-images.githubusercontent.com/24892801/93372182-70fbb080-f84b-11ea-93aa-c22db6ba4d7e.PNG)

**Comment by Adharshd** [comment]
@rashmidevapura Can you please check this issue?

**Comment by rashmidevapura** [comment]
@Teja-swi  : Initial design developed like after clear button need to click search button to get the results...in order to change it has major impact.Not changing at now as high priority.

**Comment by Tatireddysreevani** [comment]
working now.....
