### ISSUE TITLE
[Cloud-TST] Mapping a new technology (it allowing to add same existing technology) - resulting to a duplicate.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#165]
Forgot whether i logged in as partner or sme, 
But, when i am trying to add a new technology stream, if we add a new stream as an existing one, its getting added - resulting to a duplicate.,
![AddTechnologyStreamMapping_Duplicate](https://user-images.githubusercontent.com/24892801/93372944-891fff80-f84c-11ea-859c-d478a81da528.PNG)

**Comment by Adharshd** [comment]
@sivabluemix It is working for me in local as you cann see the below error message when I tried to add MEAN Stack twice. 
![image](https://user-images.githubusercontent.com/8875515/94126956-ed0e7d80-fe75-11ea-9077-c29d54564d5b.png)

**Comment by Tatireddysreevani** [comment]
closing as working fine
