### ISSUE TITLE
[Cloud-TST] Mapping a Candidate to Open Position using DWP-Mgmt

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#166]
![Mapping A Candidate to Open Position Using DWP-Mgmt](https://user-images.githubusercontent.com/24892801/93387281-de660c00-f860-11ea-897a-43bb49970fc1.PNG)

**Comment by Adharshd** [comment]
@rashmidevapura Can you tell us whether this is a valid response?

**Comment by Harshitha-Edpuganti** [comment]
@Adharshd  yes, it's a valid response.

**Comment by Adharshd** [comment]
@sivabluemix Yes, this is a valid response for your inputs as per the above comments.
