### ISSUE TITLE
Technology stream is accepting duplicate values

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#169]
Technology stream is accepting duplicate values

![image.png](https://images.zenhubusercontent.com/5ee70571210454c96d9aacda/14df99d7-bdd2-4408-81c2-7ef71cf70b6e)

**Comment by Adharshd** [comment]
Valid issue - but this already raised by Siva here: https://github.com/rkulkar5/OnlineTAT/issues/165
