### ISSUE TITLE
Not able to update Pre technical interview form all the three times, able to update only once per a candidate

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#170]
Logged in as candidate and attempted the quiz with 100% score, updated pre technical interview form first time. Second time and third time also attempted with same score, but not able to update the form. Tried with different scenario like first time got failed, second time passed and updated form, third time not able to update

**Comment by Adharshd** [comment]
@Tatireddysreevani would you mind testing again? 
can you tell me what is the error message the third time when you were not able to update?

**Comment by Tatireddysreevani** [comment]
after passing the quiz, i am getting pre technical form but not able to fill answers. Its getting disabled

**Comment by Adharshd** [comment]
@Tatireddysreevani can you share the candidate username and pw so that it is easier to recreate the issue?

**Comment by Tatireddysreevani** [comment]
candwp1@in.ibm.com
now when i am trying to attempt quiz second time, getting screen like this
![image](https://user-images.githubusercontent.com/61975055/94712708-7850ad00-0367-11eb-8484-b7448adb6d71.png)

**Comment by Adharshd** [comment]
@Tatireddysreevani can you tell me whether you passed the test previously? Because, once you pass with a candidate - one should always get the stage 2 pre-tech form and not the stage-1 online test again. 

Coming to the blank screen - it is possible that we ran out eligible questions as the previous attempts' questions should not repeated.

**Comment by Tatireddysreevani** [comment]
yes Adharsh, i passed the test previously. May be that could be the reason.

**Comment by Tatireddysreevani** [comment]
If that is the case like one person can fill form only once, i will close the issue

**Comment by Adharshd** [comment]
@Tatireddysreevani : If you have completed the quiz and also the pre-tech form and if you try to login again - you get error msg: 
![image](https://user-images.githubusercontent.com/8875515/94718706-bce04680-036f-11eb-8a45-5bdba44aed62.png)

If that is not happening - then we need to check the same. 

@rkulkar5 : can you tell whether user candwp1@in.ibm.com has completed both the online test and pre-tech form in cloud DB?
