### ISSUE TITLE
Super Admin - Add account

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#171]
a) Account Field is accepting special characters. 
![image.png](https://images.zenhubusercontent.com/5ee70571210454c96d9aacda/e6a4bbf0-51a6-41c6-bb9e-a179101eec04)

b) when trying to add existing account, not getting popup like this account already exists.
c)There is no option to delete or edit Accounts.

**Comment by Adharshd** [comment]
Found this could be an issue in every text input.

**Comment by Adharshd** [comment]
Marked as new requirement - so that other priority issues can be fixed initially

**Comment by ranjeetibm** [comment]
Fixed. Have checked-in the code to git.
Today or 2maro morning code will be deployed to cloud and will be available for the testing.

**Comment by Tatireddysreevani** [comment]
Issue fixed
