### ISSUE TITLE
Account level Admin- Edit option is not there for job role list

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#172]
Suppose if we want to delete or edit job role, delete and edit options are not there.

![image](https://user-images.githubusercontent.com/61975055/93595102-c0211d00-f9d4-11ea-877e-3b408055bf55.png)

**Comment by Adharshd** [comment]
Since this is not discussed before - marked as new requirement.

**Comment by deekshanagesh08** [comment]
Defect fixed.Kindly test

**Comment by Tatireddysreevani** [comment]
issue resolved
![image](https://user-images.githubusercontent.com/61975055/102749306-d0f17e00-4389-11eb-841d-73bcffc1669c.png)
