### ISSUE TITLE
Account level Admin- Edit option is not there in technology stream list

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#173]
![image](https://user-images.githubusercontent.com/61975055/93595257-0b3b3000-f9d5-11ea-8199-b6dbd8f8e7bc.png)

![image](https://user-images.githubusercontent.com/61975055/93595266-0f674d80-f9d5-11ea-8362-7fb6cd82bbb4.png)

Here after adding technology stream, if we want to edit account or something edit option is not there.

**Comment by Adharshd** [comment]
@Tatireddysreevani This was done on purpose. Since, it is very easy to delete and create a new tech. stream or mapping - there is no edit option provided.

**Comment by Tatireddysreevani** [comment]
It was done as per requirement
