### ISSUE TITLE
Account level Admin- Delete option is not there for test configuration list

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#174]
![image](https://user-images.githubusercontent.com/61975055/93595407-51908f00-f9d5-11ea-9a6a-d881dc029b64.png)

![image](https://user-images.githubusercontent.com/61975055/93595417-55bcac80-f9d5-11ea-8360-b56200dd07dc.png)

In test configuration list delete option is not there.

**Comment by Adharshd** [comment]
@Tatireddysreevani the delete option is not required here.

**Comment by Tatireddysreevani** [comment]
Delete option is not necessary as per the requirement
