### ISSUE TITLE
[Cloud-TST] Logged In as TECH-SME,  Under 'View Questions' Page, Logout should be right aligned.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#175]
![image](https://user-images.githubusercontent.com/24892801/93671721-4b65e580-fa9d-11ea-9360-2b521e730671.png)

**Comment by Adharshd** [comment]
@deekshanagesh08 @deenagesnagesh can you check this issue?

**Comment by Tatireddysreevani** [comment]
issue resolved
