### ISSUE TITLE
[Cloud-TST] Logged In as Sector Tech SME, Navigation Bar Issue

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#176]
Logged in as Sector Tech SME, Below is the initial display navbar.,
![image](https://user-images.githubusercontent.com/24892801/93671763-b1eb0380-fa9d-11ea-8aa3-72a0aa913942.png)

after clicking or navigation to view questions, then nav bar is changing.,
![image](https://user-images.githubusercontent.com/24892801/93671777-d050ff00-fa9d-11ea-9e95-2fe22b69538b.png)

**Comment by sivabluemix** [comment]
Please have a look at why the Nav Bar is changing compare to the initial login ?.,

**Comment by Adharshd** [comment]
Assigned to @Adharshd

**Comment by Adharshd** [comment]
@sivabluemix can you please test again?

**Comment by sivabluemix** [comment]
Its working, So closing.,
