### ISSUE TITLE
No Popup after adding a Job Role.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#177]
Logged in as DWPAdmin > Manage Metadata > I  Added a Job Role  Successfully.,

(Question/Defect) But, It is not giving any popup or alert - saying, its added successfuly.,

**Comment by Adharshd** [comment]
@rashmidevapura Can you tell us whether a popup is necessary here?

**Comment by rashmidevapura** [comment]
Yes we can add a confirmation message that it is added successfully.

**Comment by rashmidevapura** [comment]
Added popup, assigning to Siva back

**Comment by Teja-swi** [comment]
![image](https://user-images.githubusercontent.com/66815529/94371268-d2a50000-0112-11eb-8107-83a196c562e7.png)
