### ISSUE TITLE
[cloud-tst] account field is not displaying on Edit Question page.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#178]
Logged in as DWP-Admin, Navigated to Edit Question Screen, below few options are not displaying.,

Technology Stream,
Complexiy Level.,

**Comment by sivabluemix** [comment]
sorry,
account field is the one not displaying on edit question page.,

**Comment by Adharshd** [comment]
@ranjeetibm Can you tell us whether you sre still working on this so as part of Sprint-10? if so, we can close the issue.

**Comment by Adharshd** [comment]
@ranjeetibm @sivabluemix  Its also possible - this code is not part of IBM cloud- though not sure

**Comment by Adharshd** [comment]
Found this is still worked on by Deeksha - and it will take time to finish this Sprint-10 task. @sivabluemix Hence can you close this?

**Comment by sivabluemix** [comment]
Okay, closing this as its moved to spring10#task.,
