### ISSUE TITLE
[Cloud-TST] Search Lable on View Questions is slightly right aligned.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#179]
View Questions Page:
The search label is slightly misaligned, I believe, If it's a valid question then can it be left-aligned.,

![image](https://user-images.githubusercontent.com/24892801/93671905-aa782a00-fa9e-11ea-8ae5-e1e0df1efc19.png)

**Comment by Adharshd** [comment]
@deekshanagesh08 @deenagesnagesh can you please check the same?

**Comment by Tatireddysreevani** [comment]
issue got resolved
