### ISSUE TITLE
[Cloud-TST] Logged In As DWP-Admin, No Popup on Successful Open Position Creation.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#180]
Logged in as DWPAdmin > Manage Metadata > I  Added a New Open PositionSuccessfully.,
(Question/Defect) But, It is not giving any popup or alert - saying, its added successfully.,

Note: The newly added Position  is able to display in the "Open Positions List", No Issue.

**Comment by Adharshd** [comment]
Assigned ti @samirghoshibm

**Comment by samirghoshibm** [comment]
Alert message is added when Open Position is created. Please verify.

**Comment by Teja-swi** [comment]
![image](https://user-images.githubusercontent.com/66815529/94371214-94a7dc00-0112-11eb-91c4-98e35365104f.png)
