### ISSUE TITLE
[Cloud-TST] Logged In as DWP-Admin, Search Lable Mis-aligned on View Results Page.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#181]
View Results Page:
Search lable is slightly mis aligned, I believe, If its a valid question then can it be left aligned.,

**Comment by Adharshd** [comment]
@sivabluemix Can you add a screenshot of the misalignment? 

Assigned also to Rashmi in the mean time.

**Comment by rashmidevapura** [comment]
@sivabluemix : Fixed the alignment... please verify

**Comment by sivabluemix** [comment]
closed!!
