### ISSUE TITLE
[Cloud-TST] technology logo is not loaded.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#182]
![image](https://user-images.githubusercontent.com/24892801/93746603-4e6feb80-fbed-11ea-960e-a35838a17e3c.png)

**Comment by Adharshd** [comment]
@sivabluemix @rkulkar5 this seems to be fine in Local(I also dont have any logo between Node.JS and Python logos). Can you check whether this issue happens all the time in cloud?

**Comment by rkulkar5** [comment]
The image with .PNG extension was missing on cloud (there are two images one with .JPG and one with .PNG extenstions)
This has been fixed

**Comment by sivabluemix** [comment]
working, so closing.,
