### ISSUE TITLE
[Cloud-TST] Seach leable mis aligned on View Open Positions

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#183]
![image](https://user-images.githubusercontent.com/24892801/93747154-32b91500-fbee-11ea-9eeb-184a9ef42368.png)

**Comment by Adharshd** [comment]
@rashmidevapura Can you please check this?

**Comment by rashmidevapura** [comment]
Fixed and assigned back to Siva

**Comment by rashmidevapura** [comment]
![image](https://user-images.githubusercontent.com/61687054/93751124-32cf0a00-fc1a-11ea-9c4a-86d8d27d2971.png)
