### ISSUE TITLE
[Cloud-TST] Open Position ID is not showing as Number data type

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#184]
![image](https://user-images.githubusercontent.com/24892801/93747956-63e61500-fbef-11ea-8aad-3acc00b947a3.png)

**Comment by Adharshd** [comment]
@samirghoshibm Can you please check this? 

I will also add that this issue is raised after testing via Cloud alone and not the latest in Git.

**Comment by rashmidevapura** [comment]
Delete all existing open positions in the database and create one will work fine..
