### ISSUE TITLE
[Cloud-TST] some extra hyperlink on Mapping Technology Stream to Job Role.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#185]
![image](https://user-images.githubusercontent.com/24892801/93748703-99d7c900-fbf0-11ea-9fa4-ea752718c2a8.png)

**Comment by ranjeetibm** [comment]
Fixed. Please retest once the code is redeployed.

**Comment by Teja-swi** [comment]
![image](https://user-images.githubusercontent.com/66815529/94371168-0af80e80-0112-11eb-8244-dbc56e502881.png)
