### ISSUE TITLE
[Cloud-TST] Login lable mis aligned

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#186]
![image](https://user-images.githubusercontent.com/24892801/93750128-e9b78f80-fbf2-11ea-852d-abe2f07a21f3.png)

**Comment by Teja-swi** [comment]
![image](https://user-images.githubusercontent.com/66815529/94371146-dc7a3380-0111-11eb-95df-d34a21c5d024.png)
