### ISSUE TITLE
[Cloud-TST] Technical Assessment Interview - Search Label mis-aligned.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#187]
![image](https://user-images.githubusercontent.com/24892801/93753343-ec68b380-fbf7-11ea-8c13-14692bfeee38.png)

**Comment by rashmidevapura** [comment]
Fixed and checked in the code..please verify..

**Comment by Teja-swi** [comment]
fixed
![image](https://user-images.githubusercontent.com/66815529/94371117-a76de100-0111-11eb-8a63-04f16f25538f.png)
