### ISSUE TITLE
[Cloud-TST] Technical Interview Assessment - Total number of records are not exactly displaying.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#188]
There are two records (at min) displaying on screen, but the count in pagination is not correct.,
![image](https://user-images.githubusercontent.com/24892801/93753907-c7c10b80-fbf8-11ea-8dcd-fa0a770ab588.png)

**Comment by rashmidevapura** [comment]
Its data issue..delete all records and create new ones..

**Comment by sivabluemix** [comment]
Working!!
