### ISSUE TITLE
[Cloud-TST] Candidate (dwp) finished the exam, pre-tech form and can now be displayed on DWP-Tech SME, but not under sector tech sme.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#189]
![image](https://user-images.githubusercontent.com/24892801/93755619-854cfe00-fbfb-11ea-9d85-ad59d9d5f1dd.png)

**Comment by Adharshd** [comment]
@sivabluemix  Can you please retest this issue in cloud? Thank you.

**Comment by Tatireddysreevani** [comment]
working.........
