### ISSUE TITLE
[Cloud-TST] View Candidates screen few functionalities are not working.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#190]
1) Created a candidate for the DWP account and that candidate completed the exam, pre-tech form, but this candidate is visible when we logged in as DWP-Tech SME, but not as Sector-Tech-SME.,

2) I believe, there is should be enable/disable buttons , but its showing only Enable button in all cases.

3) sorting is not working for status and attempt.,

![image](https://user-images.githubusercontent.com/24892801/93757690-1d001b80-fbff-11ea-82c0-ed3260cf51e4.png)

**Comment by rashmidevapura** [comment]
Fixed and checked in changes..please verify

**Comment by sivabluemix** [comment]
Working!!
