### ISSUE TITLE
[Cloud-TST] Logged in as superadmin, 'AddUser' should be a submenu under 'Manage User'

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#191]
I believe, the 'AddUser' should be link/sub-menu under 'manager user'.,
Please validate and do the needful.,
![image](https://user-images.githubusercontent.com/24892801/93793456-c01c5980-fc2e-11ea-80d7-65383ec90699.png)

**Comment by Adharshd** [comment]
To be discussed in scrum call whether to change the title from Add User to Manage User

**Comment by Adharshd** [comment]
@sivabluemix I would say this is correct as there is only one screen for Add, Edit, and Delete Users.

**Comment by sivabluemix** [comment]
Okay, if that is the design.,
