### ISSUE TITLE
[Cloud-TST] Logged in as DWP-Mgmt, 'Manage Open Seats - sub menu showing as View Open Seats' but actual lable is showing as 'View Open Positions'., Please make both same string.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#192]
![image](https://user-images.githubusercontent.com/24892801/93794148-a6c7dd00-fc2f-11ea-97ec-53377f38d9a6.png)

![image](https://user-images.githubusercontent.com/24892801/93794196-b34c3580-fc2f-11ea-92ec-1c20921f8d12.png)

**Comment by rashmidevapura** [comment]
Changed and checked in the change..
