### ISSUE TITLE
[Cloud-TST] While trying to take exam as a candidate (java), but question paper is coming like this.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#194]
There are 4 questions configured and configured relevant passing score etc.,

![image](https://user-images.githubusercontent.com/24892801/93882974-d252d200-fcd8-11ea-9f40-a0aad4abfdec.png)

**Comment by Adharshd** [comment]
@sivabluemix Can you tell the candidate email ID used? Is this the only candidate for which this issue occurs? One valid scenario is -- the candidate might have already been part of a test and hence few questions which appeared in the test might have become ineligible to appear again. 

@rkulkar5 Can you please check the same?

**Comment by rkulkar5** [comment]
more details would have helped us to investigate the issue (like the emailID of candidate, etc)
I am tryign to reproduce from my end

**Comment by sivabluemix** [comment]
Just now, I have created a new user 'sivacand7java@ibm.com' on cloud and tried to write exam, In the first instance after logged in as candidate, Have seen that above screen where 'NaN' displayed without any question, but in a fraction of seconds its loaded the questions and started timer. 
I think its because of the system slow, Please check once.,

**Comment by sivabluemix** [comment]
@rkulkar5

**Comment by Tatireddysreevani** [comment]
closing as its working fine now
