### ISSUE TITLE
[Cloud-TST] DWP-SME logged In, Initiated Interview - Want to see the Pre-Tech Questions but not displaying.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#195]
As a candidated, I have enetred the answers for the pre-tech questions, but its not displaying when i logged in as DWP-SME and initiated interview.

![image](https://user-images.githubusercontent.com/24892801/93885018-88b7b680-fcdb-11ea-951d-a50946d2fb8e.png)

**Comment by Adharshd** [comment]
@Harshitha-Edpuganti Can you please check the same?

**Comment by Harshitha-Edpuganti** [comment]
It's working at our end.
<img width="866" alt="Defect195" src="https://user-images.githubusercontent.com/61153996/94007942-caba2880-fdbf-11ea-8cbd-667bd4515e93.PNG">

**Comment by sivabluemix** [comment]
Hi Harshita,
I have tried in Cloud today and still its not working, Please see the screenshot, its not loading the preTechnical answers given by candidate.,
![Uploading image.png…]()

**Comment by Teja-swi** [comment]
Issue fixed

![image](https://user-images.githubusercontent.com/66815529/95430494-74291e80-0969-11eb-94a0-9f29a01c71ff.png)
