### ISSUE TITLE
[Cloud-TST] Loggedin as DWP-MGMT, trying to map a condidate to open position, this is screen is not a materialized.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#196]
![image](https://user-images.githubusercontent.com/24892801/93887159-3f1c9b00-fcde-11ea-94ee-79563514df8f.png)

**Comment by Adharshd** [comment]
@sivabluemix this is fixed in local today and you can the test the same after the next IBM Cloud deployment.

**Comment by sivabluemix** [comment]
Thanks Adharsh,   I can see the changes.,
