### ISSUE TITLE
[Cloud-TST]  LoggedIn as DWP-MGMT, trying to map a candidate to open position - Noted the menus are showing diff on each action

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#197]
when loggedin as dwp-mgmt, see the menus.,
![image](https://user-images.githubusercontent.com/24892801/93887494-ad615d80-fcde-11ea-9b28-32bf1147b5f5.png)

When we select a user and assignproject, note- the menus are changed.,

![image](https://user-images.githubusercontent.com/24892801/93887425-9884ca00-fcde-11ea-80ac-c90aec3ed44e.png)

**Comment by Adharshd** [comment]
@sivabluemix this is intentional design - as the candidate might enter values in the form and if he clicks on any nav. bar - he might lose the data entered.

**Comment by sivabluemix** [comment]
My Question is around, The change in NavBar (ie. number of NavBar items on attached above screens are different and expecting it should be consistent). Can you please check ?.,

**Comment by Adharshd** [comment]
Yes, this is because Project Assignment is a different screen. This is the same for techSME, Partner, operations.

**Comment by Tatireddysreevani** [comment]
closing as it is a intentional design
