### ISSUE TITLE
Login page 

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#199]
The alignment is not proper and one image is broken. observed same in mozilla and chrome

![image](https://user-images.githubusercontent.com/66815529/93976666-ed841700-fd96-11ea-90e6-d9791c25a415.png)

**Comment by Adharshd** [comment]
To be discussed in Scrum Call.

**Comment by Adharshd** [comment]
Found that the missing image issue is fixed.

**Comment by deekshanagesh08** [comment]
Issue fixed. Kindly test

**Comment by Teja-swi** [comment]
Hi @deekshanagesh08  , Is it fine to have empty space below ?

![image](https://user-images.githubusercontent.com/66815529/96959321-5fc65380-151d-11eb-82bf-31514a549d79.png)

**Comment by rashmidevapura** [comment]
Fixed,please test once deployed in the cloud

**Comment by Teja-swi** [comment]
The screen below has still empty space, and the login card  is too big

![image](https://user-images.githubusercontent.com/66815529/97701350-456b1780-1ad3-11eb-9c56-1e6d8c161e68.png)

**Comment by rashmidevapura** [comment]
Need that space on login ..we can not increase morethe page will not look right

**Comment by rashmidevapura** [comment]
![image](https://user-images.githubusercontent.com/61687054/97708196-65ec9f00-1ade-11eb-8e46-d0df38645e67.png)

**Comment by rashmidevapura** [comment]
looked in firefox and chrome and looks fine...if increase more page will distorts

**Comment by Teja-swi** [comment]
Rashmi ..I am talking about the white  space on below not on left and right. yeah, currently login card became too big

**Comment by deekshanagesh08** [comment]
Defect is fixed. Kindly close the defect

**Comment by Teja-swi** [comment]
@rashmidevapura  - Hi Rashmi, Can you confirm if you are ok with below space which I can still see in cloud. If ok, I can close this issues.

![image](https://user-images.githubusercontent.com/66815529/97953582-fe2ca180-1dc6-11eb-93d3-27bdda848281.png)

**Comment by rashmidevapura** [comment]
Ya its ok for me but if you think we need to reduce some more space I just removed those space and checked in...Please test once deployed in cloud and let me know if its fine.

**Comment by Teja-swi** [comment]
Issue fixed 

![image](https://user-images.githubusercontent.com/66815529/98020078-8abb7c00-1e28-11eb-9b33-3ee440ea3110.png)
