### ISSUE TITLE
Add Open seat 

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#200]
Account field is showing for Single Account admin, though he belongs to one account. Since Job role details were dependent on Account value, if a admin tries to select job role prior to account, it should display a message like "Please select Account First" etc
![image](https://user-images.githubusercontent.com/66815529/93978288-63897d80-fd99-11ea-9c19-49ddb41c519f.png)

**Comment by Adharshd** [comment]
@rashmidevapura Can you please check the same?

**Comment by rashmidevapura** [comment]
@Teja-swi : No alert is required as it is making not user frindly.changed just if single account then display by default that account value and respective JRSS values.

**Comment by Teja-swi** [comment]
Account field is populating in case of single account. Do you feel alert is not required for multi account ?

**Comment by rashmidevapura** [comment]
No alert is requid

**Comment by Teja-swi** [comment]
As a alert is not required ..closing this issue
