### ISSUE TITLE
Add Job role - Multi Account

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#201]
As a admin of DWP,NHS - I am able to add job role. But later, the account field is showing only one account value.
![image](https://user-images.githubusercontent.com/66815529/93979292-c7607600-fd9a-11ea-9777-b773df0a9461.png)
![image](https://user-images.githubusercontent.com/66815529/93979308-caf3fd00-fd9a-11ea-8d99-12f5b0506a2e.png)

**Comment by Adharshd** [comment]
@ranjeetibm can you please check this issue?

**Comment by Adharshd** [comment]
@rkulkar5 can you please check this issue?

**Comment by rkulkar5** [comment]
This has been fixed, yet to deploy on Cloud

**Comment by rkulkar5** [comment]
It is deployed on cloud, please verify and close (if it works)

**Comment by Teja-swi** [comment]
Issue fixed
