### ISSUE TITLE
Add Job Role:: Only In the case of Multiple Account Admin - Account Drop down for Multiple Account admin user

### ISSUE THREAD

**Issue by Adharshd** [rkulkar5/OnlineTAT#203]

**Comment by Teja-swi** [comment]
Hi,

Able to add job role. But,
2) There is no 'Search' criteria available to search particular job role.
3) Observe the No. field below, numbers are not getting incremented
![image](https://user-images.githubusercontent.com/66815529/94126992-fac40300-fe75-11ea-9d27-2848df75181f.png)
![image](https://user-images.githubusercontent.com/66815529/94127071-18916800-fe76-11ea-8014-da11008dbf0d.png)

**Comment by Adharshd** [comment]
2) The search criteria is not required as the job roles within an account will probably be around 5-10. 
3) Please retest now.

**Comment by Teja-swi** [comment]
![image](https://user-images.githubusercontent.com/66815529/94708453-412bcd00-0362-11eb-8ab5-7bf097d24f2c.png)
Issue fixed
