### ISSUE TITLE
Color Coding of Online Test Results: Pass - Green, Failed Red

### ISSUE THREAD

**Issue by Adharshd** [rkulkar5/OnlineTAT#204]
The online test score is displayed in the Dashboard, candidate list, TechSME queue, Partner queue, Operations user queue.

**Comment by Tatireddysreevani** [comment]
Pass- Green, Failed- Red is not working on Partner interview queue of partner screen

**Comment by Adharshd** [comment]
@Tatireddysreevani The reason is Red(meaning the candidate failed the online test) is not possible in Partner queue as without passing the online test - the candidate reach partner interview stage. 

If this is the only issue  - you can close this issue

**Comment by Tatireddysreevani** [comment]
![image](https://user-images.githubusercontent.com/61975055/94703746-cdd38c80-035c-11eb-95de-827016605034.png)
in partner interview of partner queue online test result is in blue colour

**Comment by Teja-swi** [comment]
Is it not required as marked below ??
![image](https://user-images.githubusercontent.com/66815529/94702482-7254cf00-035b-11eb-8f65-ad11d0aee2c4.png)

We believe color code is implemented for SME queue , so it will be implemented for partner queue as well.

**Comment by Adharshd** [comment]
I understand - I thought the issue is with only Red code. 

@samirghoshibm  Can you check the color coding in Partner/Project assignment queues? The color coding is implemented in techSME queue so far.

**Comment by samirghoshibm** [comment]
@Teja-swi , fix is implemented for this issue. Please verify this when the next build is deployed

**Comment by Tatireddysreevani** [comment]
![image](https://user-images.githubusercontent.com/61975055/95065011-1bb21100-071e-11eb-846c-a83110ec4db5.png)
still facing the issue

**Comment by Tatireddysreevani** [comment]
issue got fixed

**Comment by Tatireddysreevani** [comment]
![image](https://user-images.githubusercontent.com/61975055/96848803-811e3580-1472-11eb-9a9d-cec7ca0a7c71.png)
online test result in List of eligible candidates screen is in blue colour on partner and management queues of sector, account and multi account level

**Comment by Tatireddysreevani** [comment]
In welcome message also its not showing whether it is a partner queue or management queue. its happening in sector, account and multi account level

**Comment by samirghoshibm** [comment]
The fix has been implemented. When the next build is deployed the same can be verified.

**Comment by Tatireddysreevani** [comment]
closing as defect fixed
![image](https://user-images.githubusercontent.com/61975055/97666242-366c7100-1aa3-11eb-83d6-3d6b8ec72e77.png)
