### ISSUE TITLE
SME - Single account - Update email ID

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#205]
Created a candidate and candidate cleared test. Candidate details reflecting in SME queue. But if admin changed his email id, Candidates details were not reflecting in SME queue.

**Comment by Adharshd** [comment]
@ranjeetibm can you please check the same?

**Comment by ranjeetibm** [comment]
As discussed, assigning the defect to Rashmi.

**Comment by rashmidevapura** [comment]
As per requirement... candidate details can not be deleted or edited if candidate has completed online test stage...alert message added...checked in please verify....

**Comment by Teja-swi** [comment]
![image](https://user-images.githubusercontent.com/66815529/94661935-520a1d80-0325-11eb-9705-12e2fa293247.png)
Issue fixed
