### ISSUE TITLE
Account level partner- From date and to date is not working in search criteria of Report section in partner queue

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#207]
when we login as Partner, From date and To date is not working in search criteria of Report section.

![image](https://user-images.githubusercontent.com/61975055/94138094-269ab500-fe85-11ea-83c4-2df69628ccc1.png)

**Comment by Adharshd** [comment]
@rashmidevapura can you please check the same?

**Comment by rashmidevapura** [comment]
@rkulkar5 : Assigning to Rajesh to verify..

**Comment by rkulkar5** [comment]
The issue was introduced due to material design changes
This has been fixed and deployed on Cloud 
Please verify and close the issue
Thanks

**Comment by Tatireddysreevani** [comment]
closing as working fine.....
