### ISSUE TITLE
unable to save new Test Configuaration 

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#208]
![image](https://user-images.githubusercontent.com/66815529/94158489-10e6b900-fea0-11ea-99a0-03849f0dd714.png)

**Comment by Teja-swi** [comment]
There is a minimum duration set to 10 min ......There is no alert message popping up on the same.

**Comment by Adharshd** [comment]
@ranjeetibm can you please check the same? We need an alert that says "Test Duration(mins) should minimum 10 mins" if a test duration of <10 mins is selected.

**Comment by ranjeetibm** [comment]
Fixed and checked in the code.
Please retest once tomorrow code is redeployed to cloud.

**Comment by Teja-swi** [comment]
Issue fixed ....getting alert
