### ISSUE TITLE
Alignment was not aligned properly

### ISSUE THREAD

**Issue by Nagalakshmi97** [rkulkar5/OnlineTAT#209]
![image](https://user-images.githubusercontent.com/67039911/94161225-172a6480-fea3-11ea-867b-827f132f8a2f.png)

**Comment by Adharshd** [comment]
@Nagalakshmi97 Can you also tell me where is this screen? Thank you.

**Comment by Nagalakshmi97** [comment]
Hi,
 
When am doing one round of testing i found that screen, For exact path where it is  i will check again and get back to you
 
Thanks&regards
Mandava Nagalakshmi
 
----- Original message -----From: Adharsh <notifications@github.com>To: rkulkar5/OnlineTAT <OnlineTAT@noreply.github.com>Cc: Nagalakshmi97 <mannag10@in.ibm.com>, Assign <assign@noreply.github.com>Subject: [EXTERNAL] Re: [rkulkar5/OnlineTAT] Alignment was not aligned properly (#209)Date: Mon, Sep 28, 2020 12:53 PM 
 
@Nagalakshmi97 Can you also tell me where is this screen? Thank you.

**Comment by Teja-swi** [comment]
Management role > Dashboard > View details

![image](https://user-images.githubusercontent.com/66815529/94701135-eaba9080-0359-11eb-9a06-897e08f9d37f.png)

**Comment by Adharshd** [comment]
@Teja-swi @Nagalakshmi97  Can you highlight the alignment issues here?

**Comment by Teja-swi** [comment]
![image](https://user-images.githubusercontent.com/66815529/94715361-fcf0fa80-036a-11eb-9bcf-9fe8c126bd2d.png)
![image](https://user-images.githubusercontent.com/66815529/94715469-23af3100-036b-11eb-8198-79d037e78e92.png)
![image](https://user-images.githubusercontent.com/66815529/94715676-738df800-036b-11eb-8a3f-70582bb06407.png)

**Comment by rashmidevapura** [comment]
Fixed the issue..please verify once code is deployed to cloud..

**Comment by Teja-swi** [comment]
Issue fixed

![image](https://user-images.githubusercontent.com/66815529/95310862-84c68f80-08aa-11eb-9f5e-c9b2f8a60fd4.png)
