### ISSUE TITLE
When I login as management, "Exceptional Approve" it is not  alligned  properly and I' am unable to download CV 

### ISSUE THREAD

**Issue by Premaks** [rkulkar5/OnlineTAT#210]
![image (9)](https://user-images.githubusercontent.com/66792210/94165951-63c46e80-fea8-11ea-945f-98a03d28f5ea.png)

**Comment by rashmidevapura** [comment]
Please mark what alignment expecting

**Comment by Teja-swi** [comment]
Hi Rashmi,  I believe issues are as below

1) alignment issue - as marked below
![image](https://user-images.githubusercontent.com/66815529/94424752-5e1ca080-01a8-11eb-9068-20f9f6c5a3a0.png)
2) Unable to download/view CV, thought CV is uploaded during candidate registration

**Comment by rashmidevapura** [comment]
Fixed..please verify after cloud deployment

**Comment by Teja-swi** [comment]
Issue fixed
