### ISSUE TITLE
Contractor in not getting questions during exam

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#211]
![image](https://user-images.githubusercontent.com/66815529/94239164-04f60800-ff2f-11ea-9202-83fe9853bd2e.png)

**Comment by rashmidevapura** [comment]
Fixed the issue for contractor quiz and all questions for contractor type are from complex level

**Comment by rashmidevapura** [comment]
Checked in ..please verify once deployed to cloud

**Comment by Teja-swi** [comment]
Contractor is getting exam - all complex questions
