### ISSUE TITLE
Pre-technical Form/Candidate details - Sector SME /Account level SME

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#212]
![image](https://user-images.githubusercontent.com/66815529/94240904-91a1c580-ff31-11ea-8140-359ac5d6d51a.png)
Candidate details were not loading in Sector SME and even pre-technical form is not loading. Logout option is needed in below page?
![image](https://user-images.githubusercontent.com/66815529/94243482-16daa980-ff35-11ea-8ff7-f46054b33288.png)

**Comment by Adharshd** [comment]
@rashmidevapura I think this was discussed during the scrum call sometime recently - can you explain in what scenarios the blank candidate is possible in the queue? 

@rkulkar5 I am unable to recreate the blank pre-tech form in local - can you please check the same in cloud?

**Comment by rashmidevapura** [comment]
Might the data is not in sync ...the  results and candidate table data not matching...user name might be edited... Several reasons ....now as per in Amit call we should not edit or delete the candidates once he progressed after initial registration....

**Comment by rashmidevapura** [comment]
Please test this scenario again after data clean up....

**Comment by Teja-swi** [comment]
Tested after data clean up ...candidate details were reflecting properly in SME/partner queue.

But, Pre-technical Forms are still not loading in cloud.

**Comment by Adharshd** [comment]
@rashmidevapura @rkulkar5 I think is another issue which works in local but not in cloud.

**Comment by rashmidevapura** [comment]
@Harshitha-Edpuganti :Please verify this...

**Comment by rkulkar5** [comment]
Please test the pre tech form questions that were not loaded, this was due to data issue and has been fixed

**Comment by Teja-swi** [comment]
![image](https://user-images.githubusercontent.com/66815529/95312684-de2fbe00-08ac-11eb-91cb-67a73f5d907d.png)

Currently issue is faced only with Question 16.

**Comment by Teja-swi** [comment]
Issue fixed

![Uploading image.png…]()
