### ISSUE TITLE
[Cloud-TST]  Open Positions  screen and 'Manage OpenSeats' > View Open Seats screen are looking same, Why do we need to have two similar screens ?.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#213]
![image](https://user-images.githubusercontent.com/24892801/94376055-fc105c80-010f-11eb-97a6-80917dd4650c.png)

**Comment by Adharshd** [comment]
@sivabluemix The difference is in the options at the bottom of the open positions list. 

In Open Position, the option is "Find Candidate"
![image](https://user-images.githubusercontent.com/8875515/94399360-d7a29780-0184-11eb-9af3-7e3833963a50.png)

In Manage Open Seats, the options are Edit & Delete. 
![image](https://user-images.githubusercontent.com/8875515/94399426-f012b200-0184-11eb-8877-5012d0e71ecd.png)

**Comment by sivabluemix** [comment]
Understand & Closing!!
