### ISSUE TITLE
[Cloud-TST] logged in as sector tech sme., Questions not displayed, but it showing as 19 records exist.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#214]
![image](https://user-images.githubusercontent.com/24892801/94376898-5cee6380-0115-11eb-9df2-d3d9afe07cce.png)

**Comment by Adharshd** [comment]
@deekshanagesh08 @deenagesnagesh Can you check this issue? I was able to recreate the same issue in local as well. 

![image](https://user-images.githubusercontent.com/8875515/94399013-42070800-0184-11eb-8a5e-6afe797c7417.png)

**Comment by deekshanagesh08** [comment]
The issue has been fixed. Kindly do the testing and let me know if there are any issues.

**Comment by Tatireddysreevani** [comment]
closing as its working fine
