### ISSUE TITLE
[Cloud-TST] LoggedIn as sector-tech-sme, Paginator (Total records showing 9, but displaying 10 with one empty record).,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#215]
![image](https://user-images.githubusercontent.com/24892801/94377228-9a53f080-0117-11eb-8f36-3892bd685265.png)

**Comment by Adharshd** [comment]
@rkulkar5 I am not able to recreate this issue in local. Can you please check this in IBM Cloud? 

In local: 
![image](https://user-images.githubusercontent.com/8875515/94398828-ed638d00-0183-11eb-809b-793b0e733619.png)

**Comment by Adharshd** [comment]
@rkulkar5 Just saw the blank candidate at 4 - can you check why that happens?

**Comment by Tatireddysreevani** [comment]
closing as issue got resolved after cleaning up database
