### ISSUE TITLE
Add Candidate: Only can add candidates belonging to the same account/accounts that is mapped to admin

### ISSUE THREAD

**Issue by Adharshd** [rkulkar5/OnlineTAT#216]

**Comment by Tatireddysreevani** [comment]
I had created admin with DWP, ANTHEM, IDEA accounts. I am able to add candidates with DWP,ANTHEM,IDEA accounts only, not able to add candidates with other accounts

**Comment by Adharshd** [comment]
So, can you close the issue.

**Comment by Tatireddysreevani** [comment]
closing as issue got resolved
