### ISSUE TITLE
View Candidate; Only can view candidates belonging to the same account as admin.  Account field to be added to the View Candiates List

### ISSUE THREAD

**Issue by Adharshd** [rkulkar5/OnlineTAT#217]

**Comment by Tatireddysreevani** [comment]
Able to view candidates belongs to same account/accounts as admin

**Comment by Adharshd** [comment]
If so - can you close this issue. @Tatireddysreevani

**Comment by Tatireddysreevani** [comment]
In sector level, admin should be able to view candidates belongs to different account also right?
