### ISSUE TITLE
pre-techinal questions to be linked to account

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#221]
As per discussion with DEV team, these questions has to be linked to Account and JRSS.

![image](https://user-images.githubusercontent.com/66815529/94420019-2eb66580-01a1-11eb-8306-dfe5b55c7beb.png)
![image](https://user-images.githubusercontent.com/66815529/94420035-3413b000-01a1-11eb-8721-946103795e1f.png)

**Comment by Adharshd** [comment]
@rkulkar5 can you please check the issue?

**Comment by Harshitha-Edpuganti** [comment]
@Teja-swi  can you please explain the defect clearly with steps

**Comment by Harshitha-Edpuganti** [comment]
@Teja-swi Fixed. Please test and confirm

**Comment by Teja-swi** [comment]
Since this is a manual process, closing the issue
