### ISSUE TITLE
Account level sme: Not able to find to which candidate the interview has been scheduled

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#222]
![image](https://user-images.githubusercontent.com/61975055/94429832-958f4b00-01b0-11eb-89e2-64e700addce2.png)
In sme queue clicked on scheduled interview without selecting the candidate, then it shows popup message like this.
![image](https://user-images.githubusercontent.com/61975055/94429957-c4a5bc80-01b0-11eb-8fe1-05398c6029b2.png)
but opens calender 
![image](https://user-images.githubusercontent.com/61975055/94430024-e141f480-01b0-11eb-8c97-d1ad03bfc95e.png)
i had scheduled an interview and close the calender, but not able to find to which candidate the interview scheduled.
Again did same process and schedules an interview, screen came like this
![image](https://user-images.githubusercontent.com/61975055/94430409-7f35bf00-01b1-11eb-8752-4b2426ea9157.png)

can you please give me conformation like how should we know to which candidate the interview scheduled.......

**Comment by Adharshd** [comment]
@rkulkar5 I tested the same in local and was able to recreate the issue. 

When I click on Ok in the "Please select a candidate" popup - the calender model appears instead of closing the popup.

**Comment by Tatireddysreevani** [comment]
yes, we are able to schedule interview also but how should we know to which candidate interview scheduled

**Comment by Adharshd** [comment]
@Tatireddysreevani Basically - you should select the candidate radio button first - which is the first column(Action) in the queue.

**Comment by Tatireddysreevani** [comment]
Yes Adharsh, My doubt is after click on "OK" of popup message "please select a candidate" we have to return back to the screen but here calender is displaying. It should not happen right?

**Comment by Adharshd** [comment]
Yes, that is what Rajesh is currently working on.

**Comment by Tatireddysreevani** [comment]
ok

**Comment by rkulkar5** [comment]
I am currently looking at the issue, it will finished by today (01-Oct) Eod

**Comment by rkulkar5** [comment]
All the issues listed above are fixed
Please verify and confirm if it works

**Comment by Tatireddysreevani** [comment]
Issue resolved

**Comment by Tatireddysreevani** [comment]
Issue resolved
