### ISSUE TITLE
Account level management: Alignment changes required

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#223]
![image](https://user-images.githubusercontent.com/61975055/94522982-26683400-024e-11eb-8d15-baac1faed930.png)
Here Technical interview feedback and partner interview feedback need to align properly and it would be better to move "job role, online test result, pre interview form and technical interview result "  slightly right side

**Comment by Adharshd** [comment]
@rashmidevapura can you check these alignment issues?

**Comment by rashmidevapura** [comment]
On all screen it looks same way: no need to change now

**Comment by Tatireddysreevani** [comment]
closing as it is as per requirement
