### ISSUE TITLE
Able to create candidate with a JRSS, which has no Test Configuration

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#224]
![image](https://user-images.githubusercontent.com/66815529/94551539-2169ab80-0273-11eb-9a56-3914bde11782.png)
![image](https://user-images.githubusercontent.com/66815529/94551585-35ada880-0273-11eb-8ef8-e0d5497e08fc.png)

**Comment by Adharshd** [comment]
@ranjeetibm Yes, I can recreate the issue in local as well - can you please check the same?

**Comment by ranjeetibm** [comment]
Fixed the issue and checked-in the code to GIT.
Please retest once the code is deployed to Cloud.

**Comment by Teja-swi** [comment]
Issue fixed
