### ISSUE TITLE
Test Configuration - Every time new record is getting created

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#225]
![image](https://user-images.githubusercontent.com/66815529/94559919-8deaa780-027f-11eb-9cca-4cc779c8c63d.png)

**Comment by Adharshd** [comment]
@rkulkar5 this issue is not happening in local for me(in both by a) editing the existing test config or b)when creating a new test-config with same Job role). Can you please check this data in cloud?

**Comment by Tatireddysreevani** [comment]
issue resolved and working fine
