### ISSUE TITLE
Account level sme: Calculate final score is not working

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#226]
Calculate final score in Initiate technical interview screen of sme queue is not working 
![image](https://user-images.githubusercontent.com/61975055/94644169-35aab880-0306-11eb-86d7-41bf04266ae0.png)

**Comment by Adharshd** [comment]
@rashmidevapura @rkulkar5 Yes, I can recreate this issue in local as well now.

**Comment by Tatireddysreevani** [comment]
closing as working fine
