### ISSUE TITLE
Bulk upload - questions are getting updated. --- but the filling up template should be easy to understand for admin

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#228]
![image](https://user-images.githubusercontent.com/66815529/94650144-c3d96b80-0313-11eb-8c34-7c04671ca2f3.png)
Tested in Mozilla, cloud
Trying to add questions to single account.

**Comment by Adharshd** [comment]
@Teja-swi can you also add the input excel used here?

**Comment by Teja-swi** [comment]
[Bulk_Upload_Template.xlsx](https://github.com/rkulkar5/OnlineTAT/files/5303589/Bulk_Upload_Template.xlsx)

**Comment by Adharshd** [comment]
To be checked with excel which seems to work.

**Comment by Adharshd** [comment]
@Teja-swi : For the QuestionType column, the possible values are singleselect or multiselect whereas previously you provided as single. I have made that change in the excel. 
[Uploading Bulk_Upload_Template(1).xlsx…]()

**Comment by Teja-swi** [comment]
Can we have a drop down to Questiontype columns in the draft excel sheet. You can mark it as "New requirement". For example, 
![image](https://user-images.githubusercontent.com/66815529/94679156-41fe3800-033d-11eb-9b36-583e92618e87.png)

**Comment by Adharshd** [comment]
Sure - we can mark this as new requirement

**Comment by Harshitha-Edpuganti** [comment]
@Teja-swi Added instructions for Questiontype and Complexity.

**Comment by Teja-swi** [comment]
Instructions are missing for sector sme.

![image](https://user-images.githubusercontent.com/66815529/96747724-41117100-13e6-11eb-9290-37a559f9542b.png)

**Comment by Harshitha-Edpuganti** [comment]
Done

**Comment by Teja-swi** [comment]
![image](https://user-images.githubusercontent.com/66815529/97542554-f21e9980-19ec-11eb-9676-413173ae9f8c.png)

Issue fixed
