### ISSUE TITLE
Alignment issue  - Cosmetic change

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#229]
Can Answered, Unanswered, Flagged aligned to above.

![image](https://user-images.githubusercontent.com/66815529/94650711-d99b6080-0314-11eb-83e8-2e332b168615.png)

**Comment by Adharshd** [comment]
Assigned to @Adharshd

**Comment by rashmidevapura** [comment]
@Teja-swi : Did not understand the expectation...please provide more info what is expected ?

**Comment by Harshitha-Edpuganti** [comment]
@Teja-swi Fixed

**Comment by Teja-swi** [comment]
Issue fixed
