### ISSUE TITLE
Pretechnical Form - Save Draft is not working for Regulars and Contractors

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#230]
Tested in cloud - Mozilla 

![image](https://user-images.githubusercontent.com/66815529/94652064-15372a00-0317-11eb-8c5a-8ceb8b766dda.png)

When we re-login , values are not populating

![image](https://user-images.githubusercontent.com/66815529/94652143-30a23500-0317-11eb-89bc-8aa5ec0cae23.png)

**Comment by Adharshd** [comment]
@samirghoshibm assigning to you as Rajesh, who worked on this, already has a few issues. 

I can also recreate this local.

**Comment by samirghoshibm** [comment]
Removed the attribute "status:1" in the mongodb query and verified the functionality in local which works fine. Needs to verified the same after deployment on cloud environment.

**Comment by rkulkar5** [comment]
Data issue, fixed it in cloud
No code change required, It can now be tested

**Comment by Teja-swi** [comment]
![image](https://user-images.githubusercontent.com/66815529/95312321-68c3ed80-08ac-11eb-95f6-dcc190855955.png)

![image](https://user-images.githubusercontent.com/66815529/95312517-a6c11180-08ac-11eb-87eb-bd98a6278f44.png)


Some issue with Question 16, unable to save & unable to retrieve.

**Comment by Teja-swi** [comment]
Issue fixed
