### ISSUE TITLE
Contractor details

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#231]
Since contractor will not have a band, Can we have " Type: Contractor " in contractor details
![image](https://user-images.githubusercontent.com/66815529/94654044-2170b680-031a-11eb-923d-82613361d982.png)

**Comment by Adharshd** [comment]
@Teja-swi What are the values for "Type" field?

**Comment by deekshanagesh08** [comment]
Issue has been fixed. Kindly test after deployed on cloud

**Comment by Tatireddysreevani** [comment]
![image](https://user-images.githubusercontent.com/61975055/96546558-1e893600-12c8-11eb-94e5-30abeb36933e.png)
Employee type is not updated on sme, partner and management queue

**Comment by deekshanagesh08** [comment]
Issue is fixed. Kindly test upon deploying on cloud

**Comment by Tatireddysreevani** [comment]
Employee type has not updated in eligible candidates list and project assignment screens of partner and management queue.
![image](https://user-images.githubusercontent.com/61975055/97534155-83870f00-19df-11eb-9c2c-52275bf8bb1f.png)
![image](https://user-images.githubusercontent.com/61975055/97534164-884bc300-19df-11eb-9f4d-856515e8f536.png)

**Comment by deekshanagesh08** [comment]
Fixed, Kindly test once deployed on cloud.

**Comment by Tatireddysreevani** [comment]
closing as workin fine...
![image](https://user-images.githubusercontent.com/61975055/97698645-d5f32900-1ace-11eb-8088-a1e1dedf5a83.png)
