### ISSUE TITLE
View Questions: In the case multiple account questions

### ISSUE THREAD

**Issue by Adharshd** [rkulkar5/OnlineTAT#232]
In View Questions: 

If, as a multiple account admin, you try and edit or delete a question mapped to > 1 accounts(which the admin is also mapped to) - a pop-up message should appear for conforming the same edit or delete question.

**Comment by deekshanagesh08** [comment]
When multi account admin tries to edit/delete,  a window pops up asking to confirm if the question belonging to x,y account be deleted/edited. It works fine ion local.

Can you please retest and let us know

**Comment by Teja-swi** [comment]
Delete option is adding questions more questions to the screen. After re-login or refresh, the question details were back to normal.

![image](https://user-images.githubusercontent.com/66815529/94686464-7e836100-0348-11eb-934c-c98fc85fa167.png)
![image](https://user-images.githubusercontent.com/66815529/94686477-8216e800-0348-11eb-8d72-636218341a0b.png)
![image](https://user-images.githubusercontent.com/66815529/94686519-8f33d700-0348-11eb-8172-62fe16c314da.png)

**Comment by Adharshd** [comment]
@Teja-swi Does this mean the number of questions increased from 63 to 93 after deleting one question "Medium docker 30/9"? 

@deekshanagesh08 can you please check the same?

**Comment by Teja-swi** [comment]
@Adharshd - Yes, But if we re-login everything is good and as expected.

**Comment by deekshanagesh08** [comment]
Defect is fixed. Kindly test and let me know if there are any issues

**Comment by Teja-swi** [comment]
Issue fixed, But I think popup is showing different message 


![image](https://user-images.githubusercontent.com/66815529/95432879-dcc5ca80-096c-11eb-9cf6-3169f99b7782.png)



below is the alert message earlier

![image](https://user-images.githubusercontent.com/66815529/95432931-f2d38b00-096c-11eb-91eb-04f4c36f9454.png)

**Comment by Teja-swi** [comment]
The alert message is not yet updated
