### ISSUE TITLE
Test Configuration - Passing Score

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#233]
Logically Passing score cannot be beyond 100.

![image](https://user-images.githubusercontent.com/66815529/94659880-90520d80-0322-11eb-939c-2fda679584e5.png)

**Comment by Adharshd** [comment]
@samirghoshibm : can you set the upper limit of passing score to 100?

**Comment by samirghoshibm** [comment]
@Teja-swi , fix is implemented. Please verify and close.

**Comment by Tatireddysreevani** [comment]
issue fixed
