### ISSUE TITLE
Admin > Test Results

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#234]
Screen is not proper

![image](https://user-images.githubusercontent.com/66815529/94661242-6ef22100-0324-11eb-8c60-2aa15fdb9479.png)

**Comment by Adharshd** [comment]
The View Results screen is okay for me in local. 

![image](https://user-images.githubusercontent.com/8875515/94662551-2dfb0c00-0326-11eb-968e-e47d240e6f8d.png)

@Teja-swi : Have you not completed even one online test for this account that you using here?

@rkulkar5 : can you check the data in cloud?

**Comment by Teja-swi** [comment]
@Adharshd : I have finished for more than one candidate.

**Comment by rashmidevapura** [comment]
@Teja-swi :Could you confirm retest the scenario and confirm whether still this issue exists?

**Comment by rkulkar5** [comment]
I too have verified the issue does not exists anymore, please make couple of check and close if it works
Thanks

**Comment by Teja-swi** [comment]
![image](https://user-images.githubusercontent.com/66815529/95311258-fdc5e700-08aa-11eb-9e64-e1c7785e8981.png)

Issue fixed
