### ISSUE TITLE
Initiate interview Screen > Technology stream values are getting duplicated

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#235]
![image](https://user-images.githubusercontent.com/66815529/94695919-1f2b4e00-0354-11eb-9a11-9a06b65970c2.png)

**Comment by Adharshd** [comment]
I this has to be fixed as we found in the meeting.

**Comment by rkulkar5** [comment]
Fixed, It can be tested on cloud on 07-Oct

**Comment by Tatireddysreevani** [comment]
Issue fixed
