### ISSUE TITLE
Initiate Partner Interview screen

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#236]
![image](https://user-images.githubusercontent.com/66815529/94700418-138e5600-0359-11eb-9fb4-62743256cc7c.png)
![image](https://user-images.githubusercontent.com/66815529/94700559-3d477d00-0359-11eb-9516-6fa2592914f6.png)

Feilds were not aligned properly

**Comment by Adharshd** [comment]
@rashmidevapura Can you check this issue?

**Comment by rashmidevapura** [comment]
Fixed the issue,checked in...please verify once it is deployed

**Comment by Teja-swi** [comment]
Hi @rashmidevapura 
Can we make either elements/keys  or the values Bold.

For example,

 **Name** : Tejaaswi    **Job** **Role** : Java technical assessment
OR 


 Name : **Tejaaswi**    Job Role : **Java** **technical** **assessment**

**Comment by rashmidevapura** [comment]
@Teja-swi : please close this issue, label bold is not required...

**Comment by Teja-swi** [comment]
As discussed, Labeling cannot be implemented. Alignment has been modified.
