### ISSUE TITLE
If admin deleted questions, assessment details were blank for candidate in SME queue.

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#237]
![image](https://user-images.githubusercontent.com/66815529/94709213-1db55200-0363-11eb-965a-bc91a1e387db.png)

**Comment by Adharshd** [comment]
@rashmidevapura @rkulkar5 is it fine to lose this "Assessment Details" data when admin decides to delete the question itself?

**Comment by Teja-swi** [comment]
![image](https://user-images.githubusercontent.com/66815529/94783080-cad2ad80-03e9-11eb-8e68-b0b1b4ca1e13.png)
some times , the mapping is wrong. the exam is written on 29th .....but it is showing question which I inserted on 30th

**Comment by rashmidevapura** [comment]
yes its fine if deliberately admin deleted those questions...then it will not appear

**Comment by rashmidevapura** [comment]
As per discussion, we should not edit/delete if question already appeared in quiz. Also in case of delete , it is soft delete changing only status to Inactive. Code checked in....please verify once deployed in cloud...

**Comment by Teja-swi** [comment]
Working fine as we are not deleting the questions in question bank.
