### ISSUE TITLE
Sector SME - Add questions

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#238]
Questions added to 'SECTOR' were not reflecting account level

![image](https://user-images.githubusercontent.com/66815529/94778998-d1f6bd00-03e3-11eb-998b-44b5d5bb4a7e.png)

**Comment by Adharshd** [comment]
@Teja-swi You mean you can't see them in "View Questions" of admin?

@deekshanagesh08 : can you tell whether questions mapped to "sector"(case-insensitive) will be part of view questions screen?

**Comment by deekshanagesh08** [comment]
Defect is fixed. Testing can be performed once deployed on cloud

**Comment by Teja-swi** [comment]
Issue fixed
