### ISSUE TITLE
Initiate Partner interview  - alignement issue  

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#239]
![image](https://user-images.githubusercontent.com/66815529/94785803-c90ae900-03ed-11eb-9410-a1006c302193.png)

Feilds were disbursed

**Comment by Teja-swi** [comment]
![image](https://user-images.githubusercontent.com/66815529/94786139-33238e00-03ee-11eb-9fe1-bd77c7f02526.png)

**Comment by Teja-swi** [comment]
![image](https://user-images.githubusercontent.com/66815529/94786139-33238e00-03ee-11eb-9fe1-bd77c7f02526.png)

**Comment by Adharshd** [comment]
Marked as New requirement as this was accepted design previously.

**Comment by rashmidevapura** [comment]
Fixed issue..please verify once deployed on cloud

**Comment by Teja-swi** [comment]
Hi @rashmidevapura
Can we make either elements/keys or the values Bold.

For example,

Name : **Tejaaswi** Job Role : **Java** **technical** **assessment**
OR

**Name** : Tejaaswi **Job** **Role** : Java technical assessment

**Comment by rashmidevapura** [comment]
@Teja-swi : Please close this issue

**Comment by Teja-swi** [comment]
As discussed, Labeling cannot be implemented. Alignment has been modified.

![image](https://user-images.githubusercontent.com/66815529/95204815-38277980-0802-11eb-8682-53e0154f14a5.png)
