### ISSUE TITLE
Sector Management user > Add Open Seat

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#243]
Sector Management user > Add Open Seat

Accounts were not getting listed

![image](https://user-images.githubusercontent.com/66815529/95173105-de10bf00-07d5-11eb-8880-56a12bda8502.png)

**Comment by rashmidevapura** [comment]
@Teja-swi :Fixed the issue...please verify once deployed

**Comment by Teja-swi** [comment]
Issue fixed
![image](https://user-images.githubusercontent.com/66815529/95428166-455d7900-0966-11eb-934b-e620bcffaa7d.png)
