### ISSUE TITLE
Account field is missing in 'View Open seats' in Sector Management role.

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#244]
Account field is missing in 'View Open seats' in Sector Management role.

![image](https://user-images.githubusercontent.com/66815529/95174250-722f5600-07d7-11eb-85ea-db15af5a8bf0.png)

**Comment by Teja-swi** [comment]
Similarly for Open Positions and eligible candidates

![image](https://user-images.githubusercontent.com/66815529/95176144-14503d80-07da-11eb-9d9b-7fcee8b3d017.png)

![image](https://user-images.githubusercontent.com/66815529/95176239-377aed00-07da-11eb-872f-9ab38986c5d5.png)

**Comment by Teja-swi** [comment]
Account field is missing in' Open Positions' for multi-account management role

![image](https://user-images.githubusercontent.com/66815529/95286764-d0b10e80-0881-11eb-9b0e-3bd2629a0329.png)

**Comment by rashmidevapura** [comment]
@Teja-swi :Fixed and please verify once deployment finished...

**Comment by Teja-swi** [comment]
Issue fixed

![image](https://user-images.githubusercontent.com/66815529/95428046-1941f800-0966-11eb-819b-77adf7af54d1.png)
![image](https://user-images.githubusercontent.com/66815529/95428112-2fe84f00-0966-11eb-800d-94ea9ca4c656.png)
