### ISSUE TITLE
Unable to assign a Failed Candidate/ unrecruited  to another account.

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#245]
Unable to assign a Failed Candidate/ unrecruited  to another account.

![image](https://user-images.githubusercontent.com/66815529/95291609-80d84480-088d-11eb-9139-0a6c973d6d9a.png)

**Comment by rashmidevapura** [comment]
@Teja-swi : Not discussed as requirement this flow....
This can be marked as new requirement and can be taken up later..

**Comment by samirghoshibm** [comment]
Some more comments on this: In the above scenario, the workaround to assign an another account is to enable the candidate and then edit the candidate record.
When a candidate is enabled the quiz number will be incremented. When editing the candidate record to change the account in this scenario, is it required  initialize the quiz number to zero?
Does it require a background job in certain interval to clean up the candidate record when candidate fails?
