### ISSUE TITLE
JRSS - Pretechnical Form Questions

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#246]
Currently  Jrss linked o Pre-technical form questions are case sensitive.

For example,  Java Technical Assessment and Java technical assessment are treated as two different values.

**Comment by rkulkar5** [comment]
As discussed in the standup call, this issue arose because the data was inserted from the backend as there are no UI screens to add the pre-Tech Questions
So the question is whether do we need to have new screens or it is ok to close the defect

**Comment by deekshanagesh08** [comment]
Defect fixed. Kindly test when deployed on cloud
