### ISSUE TITLE
Content is not justified

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#248]
![image](https://user-images.githubusercontent.com/66815529/95358878-266bd200-08e7-11eb-9ae6-fb7a6e78bc44.png)

**Comment by rashmidevapura** [comment]
Fixed the defect..please test once deployed on the cloud...

**Comment by rashmidevapura** [comment]
Attaching screen shot for reference


![image](https://user-images.githubusercontent.com/61687054/95452215-8b2a3980-0986-11eb-8413-911605785c48.png)

**Comment by Tatireddysreevani** [comment]
Issue resolved
