### ISSUE TITLE
Exam of the Candidate should not trigger, if there are no adequate questions in question Bank

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#250]
Exam of the Candidate should not trigger, if there are no adequate questions in question Bank

**Comment by samirghoshibm** [comment]
Added the code fix and checked in to the repo. When the next build is deployed, it can verified.

**Comment by Tatireddysreevani** [comment]
![image](https://user-images.githubusercontent.com/61975055/96568808-f6103480-12e5-11eb-8afe-2dd48408dfc9.png)
one time i got this warning message
then again tries with other two candidates, but not getting warning message
![image](https://user-images.githubusercontent.com/61975055/96569027-3ff91a80-12e6-11eb-94a7-5890394103d0.png)
for this jobrole i added test configuration as 5 questions and 10 minutes

**Comment by Teja-swi** [comment]
@samirghoshibm - I have tested the same for two candidates in Mozilla, I didn't  get any alert message. Can you have a look at this on cloud.

**Comment by samirghoshibm** [comment]
Please verify the defect fix which is deployed on cloud and if any issue let us know. 
As part of this fix a wait spinner is added until the questions load.

**Comment by Teja-swi** [comment]
Issue resolved.

![image](https://user-images.githubusercontent.com/66815529/97541192-c26e9200-19ea-11eb-918a-05fa36ad6e2c.png)
