### ISSUE TITLE
Account level admin- Open seat ID is not updating when we edit job role of open position

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#251]
i had created one open position like this
![image](https://user-images.githubusercontent.com/61975055/95948655-98c04300-0e0e-11eb-9b6f-067f35cdd2ff.png)
![image](https://user-images.githubusercontent.com/61975055/95948688-a970b900-0e0e-11eb-84c1-8964b6117aa4.png)
then i click on edit and changed job role from Java Technical Assessment to Product manager. But here open position id is not updating.
![image](https://user-images.githubusercontent.com/61975055/95948818-efc61800-0e0e-11eb-8767-27447e93297b.png)

**Comment by samirghoshibm** [comment]
Once the openposition is created the positionID will be created based on the JRSS and the next sequence available. When editing an open position, there will be adverse impact if the positionID gets modified based on the new JRSS as there is a possibility that the same position might be already in use. So, we are not progressing with any fix for this.

**Comment by Tatireddysreevani** [comment]
closing as its designed as per requirement
