### ISSUE TITLE
Candidate exam should not trigger if 'online assessment stage' is not selected in Work Flow Configuration.

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#252]
Work Flow configured as below

![image](https://user-images.githubusercontent.com/66815529/96114672-8e33a580-0f03-11eb-9f22-77edda31a74b.png)

Later two records of same candidate are available in Test Results(admin page) and also in Partner Interview queue.
![image](https://user-images.githubusercontent.com/66815529/96115149-20d44480-0f04-11eb-9a71-e1038de92e90.png)

![image](https://user-images.githubusercontent.com/66815529/96115232-3e091300-0f04-11eb-9931-9fa74c05f2d0.png)

**Comment by Teja-swi** [comment]
As per our discussion, Candidate exam should not trigger if 'online assessment stage' is not selected.

**Comment by rkulkar5** [comment]
Resolved the issue, please verify

**Comment by Teja-swi** [comment]
Issue fixed

![image](https://user-images.githubusercontent.com/66815529/97598981-86a8ec00-1a2d-11eb-9be8-719b24d39109.png)

**Comment by Teja-swi** [comment]
Issue fixed

![image](https://user-images.githubusercontent.com/66815529/97598981-86a8ec00-1a2d-11eb-9be8-719b24d39109.png)

**Comment by Teja-swi** [comment]
Hi Rajesh, 

You have disabled the candidate initially with quiz count '1', it seems if we enable the candidate in order to let him give quiz, the attempt is incrementing  '2' . Initially the value has to be '0'. Isn't it ?


![image](https://user-images.githubusercontent.com/66815529/97600426-0e432a80-1a2f-11eb-82ef-0ad96546db4b.png)

**Comment by rkulkar5** [comment]
Hi,
When an online assessment is skipped, we should not enable the candidate. As per the discussion we had with Amit, we either could disable the button itself or do not display such candidates in the list.
And we decided to disable the button, and the code has been fixed likewise.
Please verify. 
Thanks

**Comment by Teja-swi** [comment]
Currently , In the below scenario candidate not able to login (similar to issue #282 )

![image](https://user-images.githubusercontent.com/66815529/97954374-56fd3980-1dc9-11eb-8aea-0da165bab8db.png)

**Comment by Tatireddysreevani** [comment]
closing as working fine
