### ISSUE TITLE
Mapping Technology Stream

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#253]
Job roles details has to populate based on Account, Initially it should not display any values if account is not selected

![image](https://user-images.githubusercontent.com/66815529/96267624-a7148780-0fe5-11eb-8667-9dfcdad88f78.png)

**Comment by deekshanagesh08** [comment]
Issue is fixed. Kindly test after deployed on cloud

**Comment by sivabluemix** [comment]
Sure, I will wait to get it deploy in cloud and test it later.,

**Comment by Teja-swi** [comment]
![image](https://user-images.githubusercontent.com/66815529/97535305-7539f280-19e1-11eb-96bb-b8de6053a208.png)
But still this not restricting the Job role, once I click on it ...getting job roles

![image](https://user-images.githubusercontent.com/66815529/97535497-b92cf780-19e1-11eb-807d-1423372dfe49.png)

**Comment by rashmidevapura** [comment]
Fixed please test once deployed in the cloud

**Comment by Teja-swi** [comment]
Hi Rashmi,

It is working for the first time, But if I click in 'clear' and try the same...I see same issue

![image](https://user-images.githubusercontent.com/66815529/97705274-d218d400-1ad9-11eb-80ec-4331813fd975.png)

**Comment by rashmidevapura** [comment]
:) fixed

**Comment by rashmidevapura** [comment]
:) fixed ,please test after deployment

**Comment by rashmidevapura** [comment]
:) fixed ,please test after deployment

**Comment by rashmidevapura** [comment]
:) fixed ,please test after deployment

**Comment by Tatireddysreevani** [comment]
closing as working fine
