### ISSUE TITLE
Delete/Edit question of multiple accounts

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#254]
If a question is added to DWP& NHS accounts, If DWP admin deletes that question...the question should still appear in NHS queue.

The same applies to the Edit of the question.

**Comment by rashmidevapura** [comment]
What agreed on this requirement is as below:
admin accesslevel  =DWP, he can view/edit/delete only DWP questions
admin accesslevel=NHS,he can view/edit/delete only NHS questions
admin accesslevel=DWP,NHS , he can view/edit/delete only DWP questions, NHS Questions and DWP,NHS Quetions
admin accesslevel=DWP,NHS,ANT , he can view/edit/delete only DWP questions, NHS Questions and DWP,NHS Questions and DWP,NHS,ANT questions

**Comment by rashmidevapura** [comment]
@Teja-swi : please test once deployed on cloud

**Comment by Teja-swi** [comment]
Hi @rashmidevapura 

Below are some of the findings

1) Questions added to SECTOR, where not visible at account level.
2) Multi account admin cannot edit question of a particular account.

![image](https://user-images.githubusercontent.com/66815529/96749910-09f08f00-13e9-11eb-9b8f-3f0fbeec6d20.png)

**Comment by rashmidevapura** [comment]
Please check Tejaswi

**Comment by Teja-swi** [comment]
1) logged in as sector SME, was able to edit a question without account

![image](https://user-images.githubusercontent.com/66815529/97602162-008ea480-1a31-11eb-8e21-d86c705fa167.png)

same with other users

![image](https://user-images.githubusercontent.com/66815529/97602420-477c9a00-1a31-11eb-9659-cf81cb0471af.png)

**Comment by Teja-swi** [comment]
2) Updating single select to multi select question, not asking to select more than one option.

![image](https://user-images.githubusercontent.com/66815529/97603881-e1911200-1a32-11eb-9de3-d3331e19c1ca.png)

![image](https://user-images.githubusercontent.com/66815529/97603978-fbcaf000-1a32-11eb-8942-d5698ecc906a.png)

**Comment by Teja-swi** [comment]
3) Fetching wrong question details when we click on question to view question . The issue here could be due to delete of questions.

![image](https://user-images.githubusercontent.com/66815529/97604598-acd18a80-1a33-11eb-9ddd-387a1ee67851.png)

![image](https://user-images.githubusercontent.com/66815529/97604725-cd99e000-1a33-11eb-9295-cf6961aab7fd.png)

**Comment by rashmidevapura** [comment]
Point 1 is fixed, point 2 as discussed not required that validation
@Deeksha: Point 3 need to fix

**Comment by Teja-swi** [comment]
@deekshanagesh08  - Hi Deeksha, some how issue mentioned on point 3 seems to appear , when we do edit/delete of questions


![image](https://user-images.githubusercontent.com/66815529/97955377-0c30f100-1dcc-11eb-8edb-af633fbabc8b.png)

**Comment by deekshanagesh08** [comment]
Fixed, test once deployed on cloud

**Comment by Teja-swi** [comment]
Issue will persists

![image](https://user-images.githubusercontent.com/66815529/98235585-05e77400-1f88-11eb-83bb-c0066079c0c8.png)

But,  when trying to edit it ....getting right question.

![image](https://user-images.githubusercontent.com/66815529/98235871-75f5fa00-1f88-11eb-9cf7-e45cf60c649c.png)

![image](https://user-images.githubusercontent.com/66815529/98235947-8f974180-1f88-11eb-925e-ae7b77acaed9.png)

**Comment by Tatireddysreevani** [comment]
fixed....
