### ISSUE TITLE
User should not be able to select other accounts, if 'SECTOR' is selected 

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#256]
User should not be able to select other accounts, if 'SECTOR' is selected . SECTOR should select all the accounts in front end.

![image](https://user-images.githubusercontent.com/66815529/96270899-d88f5200-0fe9-11eb-86b7-82267d8c1af3.png)

**Comment by ranjeetibm** [comment]
Fixed, please retest once code deployed to cloud

**Comment by Teja-swi** [comment]
As suggested by Rashmi, the alert should trigger as soon as user selected both sector and accounts.

![image](https://user-images.githubusercontent.com/66815529/97667775-a6c8c180-1aa6-11eb-9440-af35e23a40c4.png)

**Comment by ranjeetibm** [comment]
As discussed, please close the defect if working.

**Comment by Teja-swi** [comment]
Issue fixed

![image](https://user-images.githubusercontent.com/66815529/97678141-5c047500-1ab9-11eb-895e-66169bd832c9.png)
