### ISSUE TITLE
Sector SME/ Multi account SME - add Account feild

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#257]
Include Account field in Candidate Interview screen

![image](https://user-images.githubusercontent.com/66815529/96271472-90bcfa80-0fea-11eb-9430-dacedd325c14.png)

**Comment by Harshitha-Edpuganti** [comment]
@Teja-swi Fixed

**Comment by Tatireddysreevani** [comment]
issue got fixed
