### ISSUE TITLE
Sector Partner /Multi account Partner - add Account feild

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#258]
1) Include Account field  in Interview, Project assignment queue.

![image](https://user-images.githubusercontent.com/66815529/96271884-0f199c80-0feb-11eb-9251-30dc42a8a3b8.png)

**Comment by Harshitha-Edpuganti** [comment]
Fixed

**Comment by Teja-swi** [comment]
Issue fixed 

![image](https://user-images.githubusercontent.com/66815529/97544236-517da900-19ef-11eb-98e1-63f46c38c227.png)
