### ISSUE TITLE
Sector level Partner/Management role  - assigning candidate to a open position

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#259]
1) Project assignment

Sector level partner should be able to assign candidate to a open position which is linked to that particular account.

2) Open Position

Findcandidates should fetch candidates of that particular open position.

![image](https://user-images.githubusercontent.com/66815529/96272574-e80f9a80-0feb-11eb-83c4-4bb42db97ad5.png)

The open positions should populate in the assignment screen.

![image](https://user-images.githubusercontent.com/66815529/96272804-39b82500-0fec-11eb-83c8-ceccc4aee98c.png)

**Comment by rashmidevapura** [comment]
fixed ... once deployed in cloud please test all possible scenarios...
