### ISSUE TITLE
Multi account Partner/Management role - assigning candidate to a open position

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#260]
1) Project assignment

Multi account partner / management should be able to assign candidate to a open position which is linked to that particular account.

2) Open Position

Find candidates should fetch candidates of that particular open position.
![image](https://user-images.githubusercontent.com/66815529/96275273-278bb600-0fef-11eb-8330-e343a7dba510.png)

The open positions should populate in the assignment screen.

![image](https://user-images.githubusercontent.com/66815529/96275313-33777800-0fef-11eb-8717-3efcb282767f.png)

**Comment by rashmidevapura** [comment]
fixed the issue..once deployed to cloud ...please test all possible scenarios for project assignment

**Comment by Tatireddysreevani** [comment]
issue fixed
