### ISSUE TITLE
Questions to be shuffled during quiz

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#261]
Currently questions in the exam were not shuffled during quiz, Candidate gets all complex questions in one go followed by Medium and Simple.

**Comment by samirghoshibm** [comment]
The defect has been fixed and can be verified now.

**Comment by Teja-swi** [comment]
![image](https://user-images.githubusercontent.com/66815529/97538128-e7143b00-19e5-11eb-9dc3-bdbd68f418ad.png)

![image](https://user-images.githubusercontent.com/66815529/97538152-f4312a00-19e5-11eb-9540-5c63e63fd0b7.png)
![image](https://user-images.githubusercontent.com/66815529/97538177-feebbf00-19e5-11eb-9751-1cdab7b03ddd.png)
![image](https://user-images.githubusercontent.com/66815529/97538223-12972580-19e6-11eb-8e5d-44338c827b33.png)


Questions are getting shuffled.
