### ISSUE TITLE
View questions - Button to view question with options

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#262]
Button to view question with options in View questions Page

**Comment by deekshanagesh08** [comment]
Fixed, Kindly test once deployed on cloud.

**Comment by Tatireddysreevani** [comment]
![image](https://user-images.githubusercontent.com/61975055/97958599-86b13f00-1dd3-11eb-927e-7fbcb4712493.png)
issue fixed
