### ISSUE TITLE
[Cloud-TST] Logged in as superadmin, expected welcome , superadmin !! but missing the 'superadmin' part after logged in.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#263]

**Comment by Harshitha-Edpuganti** [comment]
@sivabluemix  This is data issue while we created superadmin from backend. It works fine after updating users collection with
db.users.update({'username':'super'},{$set:{'name':'Super'}});

**Comment by Teja-swi** [comment]
Issue fixed

![image](https://user-images.githubusercontent.com/66815529/97667631-5baeae80-1aa6-11eb-93d8-289d2073d0f6.png)
