### ISSUE TITLE
JOB Role not loaded when trying to create a new candidate

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#265]
I have logged in as a dwpadmin and trying to create a new candidate, in this process, I have selected respective values for all the elements, except JOB Role, for some reason, this drop down not loaded with any relevant job roles., but  I can see there are two job roles (Java Technical Assessment and IIB Developer) .

<img width="960" alt="JobRole_Notloaded" src="https://user-images.githubusercontent.com/24892801/96599169-43ec6300-130d-11eb-96a1-2c69f3126a72.PNG">

**Comment by deekshanagesh08** [comment]
Siva I believe you need to add open position before creating a candidate. Can you please check if open position is present and retest the scenario

**Comment by rashmidevapura** [comment]
Not open positions....technologu stream mapping and work flow should be assigned to job role

**Comment by sivabluemix** [comment]
Don't know the magic but when I tried today, its working.,

If possible - for any reason when a drop down is not able to populate then cant it show a warning/message why it was not loaded ?.,

**Comment by sivabluemix** [comment]
Agreed with the explanation given by the team and let's note it down this defect number for the future, in case if there is a possibility we can popup the reason why it's not loaded so that admins can be aware.,
