### ISSUE TITLE
Welcome screen showing 60 questions for java exam but while attempting the exam it showing 4 questions.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#266]

**Comment by sivabluemix** [comment]
Also, after submissioning the test , just before showing the results (score page), its showing some warning for a fraction of seconds., but my laptop not supported to capture the screenshot.,

**Comment by samirghoshibm** [comment]
As part of the defect #250 fix, the questions will not appear. So this is a duplicate defect (Duplicate of #250). 
Please note that we have implemented the fix for defect #250 which can be verified now.

**Comment by sivabluemix** [comment]
Working as expected, so closing the defect.,
