### ISSUE TITLE
Multi account SME - account fetching

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#268]
Accounts are not fetching properly according to the user.

![image](https://user-images.githubusercontent.com/66815529/96698411-b52e2380-13aa-11eb-82d8-0fb974c2e8c4.png)

**Comment by Teja-swi** [comment]
Same issue is observed in single account sme as well

![image](https://user-images.githubusercontent.com/66815529/96698663-06d6ae00-13ab-11eb-8def-3baba61bba7d.png)

**Comment by ranjeetibm** [comment]
Fixed. Please retest once the code is deployed to cloud.

**Comment by Tatireddysreevani** [comment]
issue resolved
![image](https://user-images.githubusercontent.com/61975055/97541530-550f3100-19eb-11eb-938f-1d0f1e27c776.png)
