### ISSUE TITLE
Schedule Interview - Display entries of other candidate 

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#269]
As discussed, Calender will display interviews scheduled for other candidates when trying to schedule a interview for an candidate.

![image](https://user-images.githubusercontent.com/66815529/96699363-ccb9dc00-13ab-11eb-90ef-f20c78d4f65e.png)

**Comment by rkulkar5** [comment]
Fixed, please verify

**Comment by Tatireddysreevani** [comment]
Issue resolved
![image](https://user-images.githubusercontent.com/61975055/97541322-f9dd3e80-19ea-11eb-9c78-def44be42319.png)
