### ISSUE TITLE
logged in with the dwpsme1, expected 'Welcome, DWPSME1!!' but its displaying as Welcome,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#270]
<img width="960" alt="DWPSME_Welcommessage_DWPSME is not displaying" src="https://user-images.githubusercontent.com/24892801/96699687-30440980-13ac-11eb-888b-b1aabfb6cb76.PNG">

**Comment by sivabluemix** [comment]
also, when i tried to initiated interview as dwpsme1, its not displaying the welcome,dwpsme1!!

![Uploading initiatedInterview_as_dwpsme1_its not showing any welcome,dwpsme1.PNG…]()

**Comment by Harshitha-Edpuganti** [comment]
@sivabluemix Fixed

**Comment by sivabluemix** [comment]
working as expected, so closing the defect.,
