### ISSUE TITLE
logged in as dwpadmin, Expect under Manager User, it will display  users related to only DWP acccount, But its displaying the Multiaccount related users., Can this validate whether its a right behavoiur or not.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#271]
![image](https://user-images.githubusercontent.com/24892801/96702422-5ae39180-13af-11eb-9d1f-f35a79f6ff2a.png)
![image](https://user-images.githubusercontent.com/24892801/96702466-62a33600-13af-11eb-8bce-63a1e787f7f0.png)

**Comment by ranjeetibm** [comment]
Fixed. Please retest once code is deployed to the cloud.

**Comment by sivabluemix** [comment]
Issue related to Edit button got fixed, but even we are not supposed to allow to delete the user if the user mapped with multiple accounts.
scenario - Here user logged in as dwpadmin and logged in user shouldn't allowed to delete users (mapped to multiple accounts).,

![image](https://user-images.githubusercontent.com/24892801/97661105-81818680-1a99-11eb-9c7a-2914dfdfe970.png)

**Comment by ranjeetibm** [comment]
Fixed. Added the alert message for Delete button too. Please retest once code is redeployed to cloud.

**Comment by ranjeetibm** [comment]
Hi Siva,
I have fixed below issue, which we discussed in today's scrum call.
Issue:
(1) If we delete any records, all records in the list is added again and counts increases.
(2) User list not getting refreshed after delete.

Please retest for multi account delete with above issues and if all looks Ok, please close the defect.

Thanks,

**Comment by sivabluemix** [comment]
Hi Ranjeeth,
Following are my observations,
Logged in as DWPAdmin, can see users pertaining to multiple accounts, when select a user 'DNAPartner' (DWP,NHS,ANTHEM) and clicked on Delete, then it generated a popup saying 'do you want to delete' , I clicked Okay. then that entire record 'DNAPartner' got disappeared from the 'view page to see users' on DWPAdmin page.,

But, when I logged in super admin, I expected 'DNAPartner' record should exist but its not visible. Can you please have a look and let me know your view and observations.,

**Comment by sivabluemix** [comment]
Working as expected.,
