### ISSUE TITLE
Currently 'Delete' option is not working properly in Mapping Technology Stream Page.

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#272]
Currently 'Delete' option is not working properly in Mapping Technology Stream Page.

![image](https://user-images.githubusercontent.com/66815529/96728100-6647b480-13d1-11eb-9ed3-e834644e2470.png)

**Comment by Harshitha-Edpuganti** [comment]
Issue is fixed.

**Comment by Teja-swi** [comment]
@Tatireddysreevani  - please test after re-deployment on cloud today

**Comment by Tatireddysreevani** [comment]
delete button is working, but if we delete technology stream the candidate is not reflecting in sme queue. Tested the below scenario.
1. created one candidate, attempted quiz and failed.
2. deleted technology stream "java" for java technical assessment.
3. second time attempted quiz, got 100% and filled pre technical form and submitted.
but it is not reflected in sme queue. 
4. login with candidate credentials without enabling, logged in and pre technical form page is opening(like when we save and draft pre technical form).

**Comment by Tatireddysreevani** [comment]
closing as working fine
