### ISSUE TITLE
Open Position is not loading in cloud, while creating a Candidate.

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#273]
Open Position is not loading in cloud, while creating a Candidate.

![image](https://user-images.githubusercontent.com/66815529/96746060-6c935c00-13e4-11eb-83db-9a1dd838aafb.png)

![image](https://user-images.githubusercontent.com/66815529/96745904-3f46ae00-13e4-11eb-8740-f12268c405a9.png)

**Comment by rashmidevapura** [comment]
The issue not exists after cloud restarted.Assigning back to Sreevani to confirm and close the defect.

**Comment by Tatireddysreevani** [comment]
open positions are not loading in multi account admin while creating candidate
![image](https://user-images.githubusercontent.com/61975055/97672756-9a496680-1ab0-11eb-9856-057cced15ce9.png)

**Comment by rashmidevapura** [comment]
Fixed issue for multiaccount,please test once deployed

**Comment by Tatireddysreevani** [comment]
closing as working fine
![image](https://user-images.githubusercontent.com/61975055/97697672-56b12580-1acd-11eb-87da-e5447ba72a5b.png)
