### ISSUE TITLE
Not able to create an admin for USFEDERAL account. After clicking on Register button, not seen any PopUp also, its not displaying in the below userslist.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#274]
![image](https://user-images.githubusercontent.com/24892801/96971096-4380e180-1532-11eb-93d6-e99af80af3ce.png)

**Comment by sivabluemix** [comment]
This i have tried with 'superadmin' and on the home screen observe, its not showing the name superadmin, its showing only Welcome.,

**Comment by Teja-swi** [comment]
Issue fixed 
![image](https://user-images.githubusercontent.com/66815529/97667601-45a0ee00-1aa6-11eb-9e2f-31f716e8e537.png)
