### ISSUE TITLE
Favicon of Talent Sourcing Tool 

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#275]
Favicon of Talent Sourcing Tool is picking the default of angular, Is it Ok to have this ?

![image](https://user-images.githubusercontent.com/66815529/97256621-87792c80-1839-11eb-9b22-cc1954ea52e9.png)

**Comment by rkulkar5** [comment]
The fav-icon icon has been changed to reflect TST,

**Comment by Teja-swi** [comment]
Still reflecting the old icon
![Uploading image.png…]()

**Comment by rkulkar5** [comment]
![image](https://user-images.githubusercontent.com/23483645/97835298-d9b9c200-1cff-11eb-8a45-dc1bb2e3c40c.png)

**Comment by rkulkar5** [comment]
Please clear browser form data, history and cookies and check once

**Comment by Teja-swi** [comment]
new favicon reflecting

![image](https://user-images.githubusercontent.com/66815529/97841603-2dcaa380-1d0c-11eb-812c-314ddbcdd2ef.png)
