### ISSUE TITLE
Pre-techform alert

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#276]
After submitting Pre-tech form not getting an alert like ' You have successfully submitted the form - Please click on close/logout to exit'

![image](https://user-images.githubusercontent.com/66815529/97538753-f2b43180-19e6-11eb-9c71-d52c94936f9d.png)

**Comment by samirghoshibm** [comment]
As suggested, alert message is added after form data submitted. Please verify once the code is deployed.

**Comment by Tatireddysreevani** [comment]
closing as working fine...
![image](https://user-images.githubusercontent.com/61975055/97698401-75fc8280-1ace-11eb-9eda-770378eab09c.png)
