### ISSUE TITLE
Alignment issue

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#277]
Alignment issue - observed this on Multi account SME user page
![image](https://user-images.githubusercontent.com/66815529/97538878-24c59380-19e7-11eb-889a-8f91bd0ab8f8.png)

**Comment by deekshanagesh08** [comment]
Fixed, Kindly test once deployed on cloud.

**Comment by Tatireddysreevani** [comment]
closing as issue got resolved

![image](https://user-images.githubusercontent.com/61975055/97700290-9974fc80-1ad1-11eb-90b5-90b993a5f251.png)
