### ISSUE TITLE
Skip 'online assessmnet' - mapping Technology stream

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#279]
Just wondering if we require below validation check, Since we are already not allowing candidate to give exam if there are no enough questions. There might be cases where 'online assessment' is skipped for a JRSS, then there is no need of questions.

![image](https://user-images.githubusercontent.com/66815529/97541679-8be54700-19eb-11eb-86ff-5a94c76bb07a.png)

**Comment by deekshanagesh08** [comment]
Working as expected. Kindly close this defect

**Comment by Teja-swi** [comment]
As discussed, closing this issue
