### ISSUE TITLE
concerns over pre-tech form 

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#280]
hi, I logged in as a candidate and identified the following observations during the form submission.,

1) If I remember correctly this pretechnical form should contain min approx 7 questions (correct me if I am wrong).
2) I am candidate from Java background but the questions on pre-tech is showing only 3 and those 3 are related to some build, gds design principles and testing., - Have we missed to load any master data entries to display more questions on this pre-tech form ?.,
3) Mainly:
a) I am expecting an alert/popup to show - I have successfully submitted the form, now its submitting successfully and grayout the fields but I would think if we give some alert/popup saying the form is submitted successfully, it gives some confidence to end user (here candidate).
b) also expecting an alert/popup after successfully uploaded a file, at the moment, I am not getting whether the attached resume is successfully uploaded or still in the background process is running.,  [Clicked choose file, selected a file, clicked Ok, then clicked 'Upload Resume' - but don't know whether the resume is uploaded successfully or not]

![image](https://user-images.githubusercontent.com/24892801/97665409-5b5fe480-1aa1-11eb-9338-4727f4ee5112.png)

**Comment by samirghoshibm** [comment]
1) Added the alert when Submitting the form.
2) Alert already present when file is uploaded, please verify this and inform.

**Comment by sivabluemix** [comment]
Hi Ranjith,
I can see an alert after clicking on upload resume. But, not seen any after clicking on submit.
Can you please check is there any alert after submitting the form.,

**Comment by samirghoshibm** [comment]
Hi Siva,

The alert is added when form data submitted. The same issue was raised as part of defect #276. The same was verified by Sreevani and she closed the defect #276. Could you please check with her for this issue.

**Comment by Teja-swi** [comment]
Issue fixed and point 1,2 are data related issues ....which can be changed in DB
