### ISSUE TITLE
Change password

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#282]
When below stages are selected, Candidate is able to login with default password, It is not asking to change password.

![image](https://user-images.githubusercontent.com/66815529/97688495-36c73500-1ac0-11eb-9ec3-1b12e8270dbf.png)

**Comment by samirghoshibm** [comment]
Code fix has been implemented which can be verified once the latest build is deployed

**Comment by Tatireddysreevani** [comment]
issue fixed
