### ISSUE TITLE
If a candidate is failed in first attempt and passed in  second attempt, then he is not reflecting in SME queue

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#284]
Tested with the below scenario
1. created one candidate, attempted quiz and failed.
2. second time attempted quiz, got 100% and filled pre technical form and submitted. But it is not reflected in sme queue.
3. After attempting quiz second time, the candidate is in inactive state but able to login with candidate credentials without enabling and its opening pre technical form page like save and draft format
![image](https://user-images.githubusercontent.com/61975055/97987522-76b05400-1e01-11eb-96b0-20dd051de73b.png)

**Comment by Harshitha-Edpuganti** [comment]
Fixed

**Comment by Tatireddysreevani** [comment]
resolved
