### ISSUE TITLE
Search 

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#286]
Should we mention as 'Keyword' instead of Account in Search

![image](https://user-images.githubusercontent.com/66815529/97988647-4bc6ff80-1e03-11eb-9b8e-7459d1200323.png)

**Comment by Teja-swi** [comment]
Same observed in Multi account SME search

![image](https://user-images.githubusercontent.com/66815529/97990616-3a332700-1e06-11eb-945f-643b1a116d87.png)

**Comment by rashmidevapura** [comment]
As discussed keyword is not suitable for field name... the column matching search is implemented... Please test once deployed in the cloud..

**Comment by Tatireddysreevani** [comment]
fixed...
