### ISSUE TITLE
Open positions are not getting closed once assigned to a candidate

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#287]
1) Open positions are not getting closed once assigned to a candidate
2) unable to see candidate is assigned to which open position id. for example in Dashborad

![image](https://user-images.githubusercontent.com/66815529/98106638-81c9b980-1ebf-11eb-9a44-557b3c6bfdd6.png)

Jeeva has been assigned to below open position, but it is still showing in the queue and also while registering other candidate.

![image](https://user-images.githubusercontent.com/66815529/98106882-bccbed00-1ebf-11eb-8539-c6c2a0de8d91.png)

![image](https://user-images.githubusercontent.com/66815529/98107011-e84ed780-1ebf-11eb-8828-fd7a865aab6d.png)

**Comment by samirghoshibm** [comment]
Checked in the code fix. Once the build is deployed the part1 of the defect can be verified.

**Comment by rashmidevapura** [comment]
checked in code for part2 also , we can see in view details open position name and id to which candidate assigned...test once deployed in code.

**Comment by Tatireddysreevani** [comment]
issue fixed
![image](https://user-images.githubusercontent.com/61975055/98347335-4b19ad80-203d-11eb-80c3-53048d89b1e6.png)
