### ISSUE TITLE
Dashboard details

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#288]
Some of the feilds are blank in dashboard, These feilds were not asked by Partner/manger to be filled.

![image](https://user-images.githubusercontent.com/66815529/98107372-75922c00-1ec0-11eb-8b7a-dfcc8510eb6a.png)

![image](https://user-images.githubusercontent.com/66815529/98107398-7f1b9400-1ec0-11eb-9127-f9e53b780ac2.png)

**Comment by rashmidevapura** [comment]
Fixed..please test once deployed into cloud.

**Comment by Tatireddysreevani** [comment]
Issue fixed..
![image](https://user-images.githubusercontent.com/61975055/98202166-74f8a480-1f57-11eb-9202-bebd6abc2b2e.png)
