### ISSUE TITLE
Issue on 'single question Validation check' for JRSS mapping

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#290]
For a multi account admin, the check is getting  applicable for all accounts rather than selected account.
![image](https://user-images.githubusercontent.com/66815529/98109105-09fd8e00-1ec3-11eb-9c07-13d597a3eeba.png)

For example, I am trying to map **Anthem -- IIB developer -- IIB**

I am able to map above though there are no questions for IIB in Anthem account, but there are IIB questions for other accounts.

**Comment by ranjeetibm** [comment]
Fixed. Please retest once code is deployed to the cloud.

**Comment by Tatireddysreevani** [comment]
issue fixed

**Comment by Teja-swi** [comment]
Facing issue for below scenario, questions are added to multi account.

![image](https://user-images.githubusercontent.com/66815529/98651640-86c7b680-2360-11eb-8e7a-cfe22f07c36f.png)
![image](https://user-images.githubusercontent.com/66815529/98651552-6dbf0580-2360-11eb-924f-f16dc99cec56.png)

**Comment by ranjeetibm** [comment]
Fixed. Please retest after code deployment.

**Comment by Teja-swi** [comment]
@ranjeetibm  - Please let us know once this is fixed for questions added to SECTOR as well.

**Comment by ranjeetibm** [comment]
Fixed the issue for account=SECTOR
Please retest once code deployed to cloud.

**Comment by Tatireddysreevani** [comment]
fixed...

**Comment by Teja-swi** [comment]
Hi Ranjeet, 


I can again see this issue for multi accounts, Can you please have a quick look.

**Comment by Teja-swi** [comment]
This check has been modified and since additional check is added during work flow configuration,closing this issue
