### ISSUE TITLE
Search criteria in view questions screen

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#291]
Here better to provide search fields for searching question and tech stream also.
![image](https://user-images.githubusercontent.com/61975055/98209281-a9269200-1f64-11eb-9214-be3facc8bc78.png)

**Comment by deekshanagesh08** [comment]
Defect fixed. Kindly test when deployed on cloud

**Comment by Tatireddysreevani** [comment]
![image](https://user-images.githubusercontent.com/61975055/100452011-5ad95e80-30de-11eb-8443-ee4cf31d8144.png)
here Account field not working and clear button also not working

**Comment by deekshanagesh08** [comment]
Defect fixed. Kindly test when deployed on cloud.

**Comment by Tatireddysreevani** [comment]
fixed....
