### ISSUE TITLE
Reports/ Dashboard

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#294]
Report/ Dashboard details are same for all management/partner role users. Information is not getting fetched based on Account/s user logged in.

For example,

Below accounts does not have 'java technical assessment' job role.

![image](https://user-images.githubusercontent.com/66815529/98345935-523fbc00-203b-11eb-84a4-5544bac3b57e.png)

![image](https://user-images.githubusercontent.com/66815529/98346055-7a2f1f80-203b-11eb-900e-5e0ef8169e3d.png)

**Comment by rashmidevapura** [comment]
Fixed dashboard changes for multi account...please test once deployed.
@Rajesh: Please take care report section if possible, otherwise we can look later , not an issue.

**Comment by deekshanagesh08** [comment]
Defect fixed. Kindly test after deployed on cloud

**Comment by Tatireddysreevani** [comment]
fixed...
