### ISSUE TITLE
logged in a dwp account, view questions, why its allowing other than account under search category ?.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#295]
![image](https://user-images.githubusercontent.com/24892801/98434263-31876d00-20f4-11eb-8bf5-9ae84619254c.png)

**Comment by rashmidevapura** [comment]
It is already taken care siva.....its already implemented this defect.

**Comment by sivabluemix** [comment]
As informed by Rashmi, I am going to close.,
