### ISSUE TITLE
Deleted questions

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#297]
Uploaded 20 questions and deleted all questions.

**Issue 1 :** When trying to map technology stream, though there are no active questions .....we are able to map technology stream.

![image](https://user-images.githubusercontent.com/66815529/98515448-1c941080-2291-11eb-9f43-564d0bc2c94b.png)

**Issue 2:**  Geeting deleted questions in quiz

![image](https://user-images.githubusercontent.com/66815529/98516211-384be680-2292-11eb-93a7-1753b3b71890.png)

I am getting deleted questions in quiz.

![image](https://user-images.githubusercontent.com/66815529/98516794-f7a09d00-2292-11eb-9ec8-2dead5223b1f.png)

**Comment by samirghoshibm** [comment]
Code fix added which can be verified after the next build is deloyed

**Comment by Teja-swi** [comment]
Issue fixed.
