### ISSUE TITLE
Alignment issue - minor

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#298]
Alignment issue 'click here'

![image](https://user-images.githubusercontent.com/66815529/98551809-c391a000-22c3-11eb-9620-94cbb14e9bb2.png)

**Comment by Harshitha-Edpuganti** [comment]
Fixed

**Comment by Teja-swi** [comment]
Issue fixed

![image](https://user-images.githubusercontent.com/66815529/98775669-9a802500-2413-11eb-88da-89ce113dc21e.png)
