### ISSUE TITLE
Not getting Pre Technical Questions for DWP and HMRC account

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#299]
created candidate and mapped to DWP account and DevOps Administrator, attempted quiz and got 80%
![image](https://user-images.githubusercontent.com/61975055/98903112-efd43900-24dc-11eb-9b99-cf6e3dc89d82.png)

clicked on link 
![image](https://user-images.githubusercontent.com/61975055/98903523-ca93fa80-24dd-11eb-81e9-2cd37b790b03.png)

after clicked on start getting page like this, not getting pre tech question
![image](https://user-images.githubusercontent.com/61975055/98903186-198d6000-24dd-11eb-82f1-d4cad0788d53.png)

Tried by creating another candidate and mapped to DWP, java technical assessment, still facing same problem.

for HMRC account and Java Technical Assessment not getting "fill pre tech form link" also, getting page like this
![image](https://user-images.githubusercontent.com/61975055/98903409-8bfe4000-24dd-11eb-90b8-20a63ca590f1.png)

for all these cases selected all stages of interview process.

**Comment by rajeshdattatraya** [comment]
Code fix done, yet to deploy on cloud

**Comment by rkulkar5** [comment]
Deployed the code, please test

**Comment by Tatireddysreevani** [comment]
issue fixed
