### ISSUE TITLE
Exception approval - Management role

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#300]
In Management user, Given exception approval for SME and partner interview before attempting quiz

![image](https://user-images.githubusercontent.com/66815529/98909493-ea302080-24e7-11eb-91bd-de9d91e87baa.png)

Before assessment,

![image](https://user-images.githubusercontent.com/66815529/98909552-fcaa5a00-24e7-11eb-8f6b-ccf95a5ce2fb.png)

Candidate is able to login and finished assessment. But, there are two records .

![image](https://user-images.githubusercontent.com/66815529/98909807-4eeb7b00-24e8-11eb-84df-1bc8f5e47a2f.png)

![image](https://user-images.githubusercontent.com/66815529/98909909-76424800-24e8-11eb-8826-a62b7504c7ff.png)

**Comment by deekshanagesh08** [comment]
Defect fixed. Kindly test when deployed on cloud
