### ISSUE TITLE
Feedback feilds

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#301]
Exception approval given for few stages

![image](https://user-images.githubusercontent.com/66815529/98911819-40529300-24eb-11eb-8935-bd3e3636d77a.png)

**Q:** Should we display below fields ??

![image](https://user-images.githubusercontent.com/66815529/98912698-717f9300-24ec-11eb-83a6-36f5b72c66a9.png)

Example2 ,

![image](https://user-images.githubusercontent.com/66815529/98913968-151d7300-24ee-11eb-92df-0c57017c2f5c.png)

![image](https://user-images.githubusercontent.com/66815529/98914043-341c0500-24ee-11eb-98e8-13032bef206f.png)

**Comment by deekshanagesh08** [comment]
Defect fixed. Kindly test when deployed on cloud

**Comment by Tatireddysreevani** [comment]
![image](https://user-images.githubusercontent.com/61975055/100072949-dfb84400-2e62-11eb-9099-47bff738e9cb.png)
Fixed...
