### ISSUE TITLE
logged in as multiaccount partner and on project assignment screen, selected a candidate and gone to the project assignment screen, identified there is no welcome banner.,

### ISSUE THREAD

**Issue by sivabluemix** [rkulkar5/OnlineTAT#302]
![image](https://user-images.githubusercontent.com/24892801/98944488-20d15f80-2517-11eb-864b-5633b39d82af.png)

**Comment by deekshanagesh08** [comment]
Defect fixed. Kindly test

**Comment by Tatireddysreevani** [comment]
fixed
![image](https://user-images.githubusercontent.com/61975055/99779022-75d62c80-2b3a-11eb-9751-ad41ca69a5f5.png)
