### ISSUE TITLE
Removing the candidate from SME/Partner list when we choose final result as "Not Suitable"

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#303]
Candidate should be removed from the sme/partner list if the final result chosen as 'not suitable'. And  candidate should be allowed to register to other account. But candidate details needs to be retained in the dashboard.

**Comment by deekshanagesh08** [comment]
Defect fixed. Kindly test

**Comment by Tatireddysreevani** [comment]
resolved
