### ISSUE TITLE
Admin Screen: Candidate Location of contractor should be captured while registering candidate.

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#305]

**Comment by deekshanagesh08** [comment]
Defect fixed. Kindly test

**Comment by Tatireddysreevani** [comment]
fixed...
![image](https://user-images.githubusercontent.com/61975055/99965599-1175d000-2dbb-11eb-8a91-b7c68fd27100.png)

**Comment by Teja-swi** [comment]
Candidate location for contractor is missing in Test results screen

![image](https://user-images.githubusercontent.com/66815529/100233145-53377f80-2f4f-11eb-90ee-1fda9ea1bf56.png)

**Comment by deekshanagesh08** [comment]
Defect fixed. Kindly test

**Comment by Tatireddysreevani** [comment]
![image](https://user-images.githubusercontent.com/61975055/100706892-cb7ac680-33cf-11eb-8c58-69be1a6c7ed4.png)
fixed.........
