### ISSUE TITLE
Account should be displayed as dropdown in view question screen.

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#306]

**Comment by Tatireddysreevani** [comment]
![image](https://user-images.githubusercontent.com/61975055/100704465-953b4800-33cb-11eb-8cce-d3736f703df6.png)
![image](https://user-images.githubusercontent.com/61975055/100704492-9d938300-33cb-11eb-928b-cd3b9b900a2b.png)
here i added some questions for DWP account only and some questions for multiple account including DWP
while searching i gave DWP account name, not getting questions in multiple accounts including DWP.
Better to have multi selecting of accounts

**Comment by deekshanagesh08** [comment]
Defect fixed. Kindly test when deployed on cloud

**Comment by Tatireddysreevani** [comment]
resolved
