### ISSUE TITLE
Logged In user name is missing in welcome message while navigating from initiate interview screen 

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#314]

**Comment by Tatireddysreevani** [comment]
Facing same problem in multi sme and sector sme when we click on the link of pre tech form

![image](https://user-images.githubusercontent.com/61975055/99957231-598df600-2dad-11eb-92c3-45b4e417604d.png)

**Comment by Harshitha-Edpuganti** [comment]
multisme/sector is fixed now.Please test

**Comment by Tatireddysreevani** [comment]
fixed...
