### ISSUE TITLE
Candidate who has failed quiz should be made available or registered by other account after  'x'(7 days) no of days 

### ISSUE THREAD

**Issue by deekshanagesh08** [rkulkar5/OnlineTAT#316]

**Comment by deekshanagesh08** [comment]
Defect fixed. Kindly test

**Comment by Tatireddysreevani** [comment]
Created one candidate and failed in quiz, then i changed DOJ to 14/12/2020 and tried to re register candidate for other candidate. That time i am getting please use other email id warning message
![image](https://user-images.githubusercontent.com/61975055/102871410-682b0400-4464-11eb-9c13-4abe65c8a66b.png)

when i click again and again on save button, candidate creating.
![image](https://user-images.githubusercontent.com/61975055/102871487-80028800-4464-11eb-94b8-3be3ab0c07d3.png)

when i tried to delete this candidate, getting as below, but i didn't attempted quiz for this candidate after re registering
![image](https://user-images.githubusercontent.com/61975055/102872026-2d759b80-4465-11eb-940e-fc7af303aa05.png)

and when i tried to attempted quiz for this candidate, its showing like this
![image](https://user-images.githubusercontent.com/61975055/102871835-ec7d8700-4464-11eb-960d-820236d13376.png)

**Comment by Tatireddysreevani** [comment]
working fine

**Comment by Tatireddysreevani** [comment]
1)created one candidate.
2)failed in quiz and edited creation date in results table
3)tried to reregister for other account, but getting erroe message
![image](https://user-images.githubusercontent.com/61975055/105469250-f2fa5b00-5cbd-11eb-8fe7-e942edda9d2a.png)

**Comment by Tatireddysreevani** [comment]
working fine
