### ISSUE TITLE
Candidate who has cleared quiz and awaiting technical SME interview should be made available or registered by other account after 'y'(7 days) number of days

### ISSUE THREAD

**Issue by deekshanagesh08** [rkulkar5/OnlineTAT#317]

**Comment by deekshanagesh08** [comment]
Defect fixed. Kindly test

**Comment by Tatireddysreevani** [comment]
fixed

**Comment by Tatireddysreevani** [comment]
facing this issue again. getting warning message while reregistering for other account.
![image](https://user-images.githubusercontent.com/61975055/105483702-3cec3c80-5cd0-11eb-8ea6-cef6bafd4e44.png)

**Comment by Tatireddysreevani** [comment]
working
