### ISSUE TITLE
Candidate awaiting partner interview should be made available or registered by other account after 'z'(7 days) number of days

### ISSUE THREAD

**Issue by deekshanagesh08** [rkulkar5/OnlineTAT#318]

**Comment by deekshanagesh08** [comment]
Defect fixed. Kindly test

**Comment by Tatireddysreevani** [comment]
fixed

**Comment by Tatireddysreevani** [comment]
again facing the same issue, not able to reassign candidate to other accounts. Getting warning message
![image](https://user-images.githubusercontent.com/61975055/105483590-162e0600-5cd0-11eb-831b-808c0995c9e2.png)

**Comment by Tatireddysreevani** [comment]
working fine
