### ISSUE TITLE
If a candidate has registered to an account multiple times, dashboard should display only latest entry of a candidate

### ISSUE THREAD

**Issue by deekshanagesh08** [rkulkar5/OnlineTAT#323]

**Comment by Tatireddysreevani** [comment]
please look into the scenario which i tested for this issue. In Test Results its showing only latest result, but in dashboard not showing.
Created candidate “Sreevani” with following details
![image](https://user-images.githubusercontent.com/61975055/103090325-c1d33000-4616-11eb-831f-f2f84fc17cec.png)

Attempted quiz and failed
![image](https://user-images.githubusercontent.com/61975055/103090075-06120080-4616-11eb-85e5-f582541dd567.png)

Changed test result date and re register for other account with following details
![image](https://user-images.githubusercontent.com/61975055/103090096-132eef80-4616-11eb-8f2a-7dca72ecc62c.png)

Attempted quiz and got 100%
![image](https://user-images.githubusercontent.com/61975055/103090115-20e47500-4616-11eb-8e0b-c892151603d5.png)

Gave “Not suitable” in sme result and re register for other account with following details
![image](https://user-images.githubusercontent.com/61975055/103090133-2b067380-4616-11eb-8661-88b520c9715a.png)

Attempted quiz again and got 80%
![image](https://user-images.githubusercontent.com/61975055/103090147-348fdb80-4616-11eb-864d-f99eccbd1ed0.png)

In Dashboard it is not showing latest one, its showing record incorrectly
![image](https://user-images.githubusercontent.com/61975055/103090163-3eb1da00-4616-11eb-9d49-4f078a8c598e.png)

**Comment by deekshanagesh08** [comment]
Sreevani to retest the scenario.

**Comment by Tatireddysreevani** [comment]
Retested the scenario and followed the following steps.
1) Created one candidate in DWP account and failed in quiz.
2) changed the creation date in results table of db, reregister for NHS account
3)Gave not suitable in SME queue and reregister for IDEA account
4)Gave not suitable in Partner queue and again Reregister for  DWP account
In Dashboard we should get record for DWP, NHS, IDEA accounts. But here i am getting only latest one.
![image](https://user-images.githubusercontent.com/61975055/103646913-76a70e80-4f80-11eb-8f78-848fe4e5e43a.png)

**Comment by rashmidevapura** [comment]
@Tatireddysreevani : As discussed it is working fine in local .... ... while testing in cloud observed it is not copied to results_hist table while registering new candidate... thats why it is not displayed in dashboard... but same scenario worked perfect in local... please clear all old data in cloud and retest with new candidate details

**Comment by rashmidevapura** [comment]
As discussed please test and confirm once deployed in cloud

**Comment by Tatireddysreevani** [comment]
fixed...

![image](https://user-images.githubusercontent.com/61975055/105318941-253a8880-5bea-11eb-8b8d-d1b2676911c3.png)
