### ISSUE TITLE
While registering a candidate, validation needs to be performed to check if candidate is available to register for other account. Candidate should be able to reregister if candidate satisfies certain conditions

### ISSUE THREAD

**Issue by deekshanagesh08** [rkulkar5/OnlineTAT#325]
While registering a candidate, validation needs to be performed to check if candidate is available to register for other account.
Candidate should be able to reregister if candidate satisfies any of the following
-Candidate who has failed quiz should be made available or registered by other account after  'x'(7 days) no of days.
-Candidate who has cleared quiz and awaiting technical SME interview should be made available or registered by other account after 'y'(7 days) number of days.
-Candidate awaiting partner interview should be made available or registered by other account after 'z'(7 days) number of days. -Candidate who has cleared partner interview and yet to be assigned to a project should be made available or registered by other account after 'w'(7 days) number of days.
- When candidate is registered to an account but they have not taken the test within 'x' no of days, then they shouldn't be allowed to register to another account.
-If SME/partner provides feedback has 'Not Suitable', candidate should be made available to register for other account.

**Comment by deekshanagesh08** [comment]
Defect fixed. Kindly test

**Comment by Teja-swi** [comment]
All these scenarios has been tested as part of other user stories and this task.
