### ISSUE TITLE
Technical Interview result in Exceptional Approval queue - Management role

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#327]
If a SME updates a candidate as Not Suitable , the value is not getting reflecting in below screen. The same is available in dashboard

![image](https://user-images.githubusercontent.com/66815529/100314741-54af8900-2fdd-11eb-9c34-3911756fa7a0.png)

![image](https://user-images.githubusercontent.com/66815529/100314771-6a24b300-2fdd-11eb-8719-8fe79e0ba982.png)

**Comment by deekshanagesh08** [comment]
Defect fixed. Kindly test

**Comment by Tatireddysreevani** [comment]
![Uploading image.png…]()
fixed....
