### ISSUE TITLE
 Report  -Todate issue , not taking todays date in to consideration

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#329]
Report  -Todate issue , not taking todays date in to consideration

**Comment by deekshanagesh08** [comment]
Defect fixed. Kindly test

**Comment by Tatireddysreevani** [comment]
![image](https://user-images.githubusercontent.com/61975055/100712997-a8edab00-33d9-11eb-902d-0453a2e19502.png)
fixed.....
