### ISSUE TITLE
Admin screen: "Pre technical questions not loaded" pop up message not coming while configuring workflow

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#333]
If pre technical questions not uploaded for JRSS, then it should show the popup message of "Pre technical questions not loaded".
But here it is not showing.
![image](https://user-images.githubusercontent.com/61975055/102318230-015aa600-3f9f-11eb-889c-1405c3632994.png)

**Comment by Tatireddysreevani** [comment]
though pre tech questions are not there, stage is getting selected and in sme queue and partner queue when we click on access pre tech questions link its showing as exceptional approval given
![image](https://user-images.githubusercontent.com/61975055/102324608-0ff98b00-3fa8-11eb-91a7-cd73719c2514.png)

**Comment by rashmidevapura** [comment]
@Tatireddysreevani :Please retest this issue and confirm whether still this issue exists...

**Comment by Tatireddysreevani** [comment]
fixed...
