### ISSUE TITLE
Partner screen: Job role is not updating in candidate details of partner queue

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#334]
I changed job role from "Designer" to "Web Designer". Its reflecting in every place except in candidate details of partner queue.
Here its showing some different code 
![image](https://user-images.githubusercontent.com/61975055/102335119-7f29ac00-3fb5-11eb-8575-3ed8be56fc43.png)

**Comment by rashmidevapura** [comment]
Fixed and checked in ..please test once deployed...

**Comment by Tatireddysreevani** [comment]
issue fixed
![image](https://user-images.githubusercontent.com/61975055/102771688-584fe900-43ac-11eb-9ddd-8a30c5a71c9b.png)
