### ISSUE TITLE
Candidate email Id

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#336]
As suggested by Rajesh, Raising this issue.

Candidate email Id should be unique.

![image](https://user-images.githubusercontent.com/66815529/102440623-9795d700-4046-11eb-8999-accdda5dee8d.png)

**Comment by ranjeetibm** [comment]
Fixed. Please rested.

Note: Latest code is deployed on cloud at around 8:40 PM and I have checked-in the code for this defect at 9:00 PM. So please start the testing once code is redeployed on Dec 24th.

**Comment by Tatireddysreevani** [comment]
fixed..
![image](https://user-images.githubusercontent.com/61975055/103090607-7ff6b980-4617-11eb-9d83-f2dc1c74e58a.png)
