### ISSUE TITLE
The calendar of SME still shows records moved to other accounts.

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#338]
1) Registered candidate on 21/12/2020 - DWP account

![image](https://user-images.githubusercontent.com/66815529/102763280-77944980-439f-11eb-9841-f6d925f6afcb.png)

2) Given exam

![image](https://user-images.githubusercontent.com/66815529/102763506-c3df8980-439f-11eb-9b17-24c97ee23cb9.png)

3) Schedule interview by SME

![image](https://user-images.githubusercontent.com/66815529/102763711-115bf680-43a0-11eb-9cd8-6eed4ccd66dd.png)

4) Update created date to 14/12/2020

![image](https://user-images.githubusercontent.com/66815529/102763872-49fbd000-43a0-11eb-9902-37a6383e790f.png)

5) re-registration of candidate by NHS account

![image](https://user-images.githubusercontent.com/66815529/102764109-9fd07800-43a0-11eb-88ea-762dce728833.png)

Issue : The calendar of SME still shows records moved to other accounts.

![image](https://user-images.githubusercontent.com/66815529/102764746-a6abba80-43a1-11eb-8ce9-936e6692e9c1.png)

**Comment by rkulkar5** [comment]
Fixed and Deployed on cloud
Please test

**Comment by Teja-swi** [comment]
Issue fixed.

![image](https://user-images.githubusercontent.com/66815529/102971489-7e49ca80-451f-11eb-82eb-f8c46a058064.png)

![image](https://user-images.githubusercontent.com/66815529/102971697-d41e7280-451f-11eb-8a04-e4195c79d1fe.png)
