### ISSUE TITLE
Comments _ exceptional approavl

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#340]
Comments were not mandatory, able to save the details without providing any comments

![image](https://user-images.githubusercontent.com/66815529/102862720-86d6ce00-4457-11eb-886b-dc31f5fb1a80.png)

**Comment by rashmidevapura** [comment]
Working on this

**Comment by rashmidevapura** [comment]
Fixed...please test once deployed

**Comment by Tatireddysreevani** [comment]
fixed
![image](https://user-images.githubusercontent.com/61975055/102994007-3b4e1e00-4544-11eb-92c9-7f9bf89a8726.png)
