### ISSUE TITLE
Candidate login

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#343]
For below scenario, Candidate tries to login,

![image](https://user-images.githubusercontent.com/66815529/102961300-f0afb000-4509-11eb-9937-0528485e4427.png)

Issue 1: It is asking to change password
Issue 2: After changing password, when trying to login with new password not able to login but **no popup/error is displaying**

**Comment by rashmidevapura** [comment]
After changing password, if candidate tries to login the proper message is displaying
Its working correctly...please let me know if any other scenario you tested.

**Comment by rashmidevapura** [comment]
![image](https://user-images.githubusercontent.com/61687054/103067704-8ff3a680-45e1-11eb-8c72-1b755e42621c.png)

**Comment by Teja-swi** [comment]
Working fine after re-deployment

![image](https://user-images.githubusercontent.com/66815529/103078635-51b5b180-45f8-11eb-823f-9d73f10f0d5d.png)
