### ISSUE TITLE
Multiple choice questions

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#345]
Summary has to be in sync with the questions answered.

![image](https://user-images.githubusercontent.com/66815529/103065888-af88d000-45dd-11eb-934b-9c6e80749a8e.png)

![image](https://user-images.githubusercontent.com/66815529/103065841-98e27900-45dd-11eb-9a2b-2b72f334507d.png)

**Comment by deekshanagesh08** [comment]
Defect fixed. Kindly test.

**Comment by Tatireddysreevani** [comment]
![image](https://user-images.githubusercontent.com/61975055/104875106-7cd2bd00-597a-11eb-8b82-74afa8785fc1.png)
![image](https://user-images.githubusercontent.com/61975055/104875117-83613480-597a-11eb-99e0-6c2b4670838e.png)


fixed
