### ISSUE TITLE
character limit

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#346]
I believe Rashmi has taken care of the below earlier. Hence raising this issue.

![image](https://user-images.githubusercontent.com/66815529/103501704-02337900-4e75-11eb-8371-9d74719f6af0.png)

![image](https://user-images.githubusercontent.com/66815529/103501731-17100c80-4e75-11eb-82f5-f79240231e0d.png)

**Comment by rashmidevapura** [comment]
Fixed added maxlength 40 on account ,jrss, candidate name fields..please test once deployed on cloud.

**Comment by Tatireddysreevani** [comment]
fixed
