### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#347]
The picture below does not give clear picture of who has given exceptional approval or to which stage the approval  is given in **'Exceptional Approval Details**.

**Suggestion:** Can we have Approver mail id added, so that management guy knows who has given exceptional approval.
'

![image](https://user-images.githubusercontent.com/66815529/103766877-9a805800-5045-11eb-8382-5b10a1ad393d.png)

**Comment by Harshitha-Edpuganti** [comment]
Fixed. Added SME Name and Partner Name fields in details

**Comment by Tatireddysreevani** [comment]
its working fine, but it would be better to change SME name to SME mail id
![image](https://user-images.githubusercontent.com/61975055/104888516-d941d680-5992-11eb-8aa9-5204329183ab.png)
