### ISSUE TITLE
Story::As a tech SME, I would like to update the tech stream score, interview result and interview feedback of each candidate

### ISSUE THREAD

**Issue by Adharshd** [rkulkar5/OnlineTAT#44]
**(As discussed, you can ignore the links and also delete and add rows buttons for this Sprint)**
The **final result** drop-down to have the options a) Highly-recommended b) Recommended c) Not suitable. 

You can find the UI Screen for initiating Tech SME interview and updating candidate details post Technical Interview here: 
![Tech SME - Inititate Interview Screen](https://user-images.githubusercontent.com/8875515/83383705-4bb17680-a403-11ea-925e-a3d7afa5b14d.png)

**Comment by anilktm** [comment]
I have developed the UI screen & Api for the requirement.
The data flow completed and code available in git.

**Comment by anilktm** [comment]
@Adharshd 

After submitting the technical SME review, Do I need to display any confirmation page?
Its not mentioned in the user story.
What's next action after the technical SME review submission?

**Comment by anilktm** [comment]
US-44 requirement completed.
