### ISSUE TITLE
Story::As a Partner, I would like to view the details of candidates in my queue

### ISSUE THREAD

**Issue by Adharshd** [rkulkar5/OnlineTAT#45]
**(As discussed, the Candidate CV link can be ignored for this Sprint)**

The UI Screen for Partner Interview Queue: 

![Partner Queue](https://user-images.githubusercontent.com/8875515/83384017-fa55b700-a403-11ea-9c39-f15178d3654c.png)

**Comment by rashmidevapura** [comment]
Closed as this user story completed
