### ISSUE TITLE
Story::As a candidate, I would like to read the questions and options before deciding on the answer 

### ISSUE THREAD

**Issue by Adharshd** [rkulkar5/OnlineTAT#5]
- [ ] UI to view the questions and options. https://github.com/rkulkar5/OnlineTAT/issues/16
- [ ] Radio Button/Check-Box provided for options in UI as per the "Question Type". 
- [ ] API/Method is needed to read the Questions and Options.

**Comment by Adharshd** [comment]
PFA the screen for questions description with options
![DWP(6)](https://user-images.githubusercontent.com/8875515/76753745-09cf4780-67a7-11ea-85cc-0938be40595f.png)
**Ignore the buttons for this user story.**

**Comment by rashmidevapura** [comment]
Closed as this user story completed
