### ISSUE TITLE
Story::As an admin, I would like to view all the candidate details(Name, email, JRSS, Score, Tech Interview, CV link, Pre-tech form) before providing exception approval.

### ISSUE THREAD

**Issue by Adharshd** [rkulkar5/OnlineTAT#83]
UI Screen shared by Amit: 

![image](https://user-images.githubusercontent.com/8875515/86709905-0a326d80-c038-11ea-8cb3-4b60c6c38548.png)

**Comment by rashmidevapura** [comment]
Closed as this user story completed
