### ISSUE TITLE
Story::As a candidate, I would like to view the summary to understand the exact flagged, answered and unanswered questions at all times

### ISSUE THREAD

**Issue by Adharshd** [rkulkar5/OnlineTAT#9]
- [ ] API/Method to get the current summary of the quiz. 
- [ ] UI of the summary page(see attached in comments).
- [ ] Enable going back to the previous question(from where the Summary button is clicked).
- [ ] Enable links to all questions in the summary. 
- [ ] Adding Summary Button in Question UI Screen. (is blocked by https://github.com/rkulkar5/OnlineTAT/issues/16)

**Comment by Adharshd** [comment]
PFA an example of the Summary Page

![DWP(14)](https://user-images.githubusercontent.com/8875515/76822946-8f4f0800-6838-11ea-92a0-9cd5bdcc2c29.png)

Summary Button in a Question Screen. 
![DWP(12)](https://user-images.githubusercontent.com/8875515/76822973-a7bf2280-6838-11ea-9612-8c2ce4101f85.png)

**Comment by rashmidevapura** [comment]
Closing the task as it is completed
